<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client\_DictionaryGetResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cache_client._DictionaryGetResponse._Found</code>
 */
class _Found extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .cache_client._DictionaryGetResponse._DictionaryGetResponsePart items = 1;</code>
     */
    private $items;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cache_client\_DictionaryGetResponse\_DictionaryGetResponsePart[]|\Google\Protobuf\Internal\RepeatedField $items
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cacheclient::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .cache_client._DictionaryGetResponse._DictionaryGetResponsePart items = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Generated from protobuf field <code>repeated .cache_client._DictionaryGetResponse._DictionaryGetResponsePart items = 1;</code>
     * @param \Cache_client\_DictionaryGetResponse\_DictionaryGetResponsePart[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cache_client\_DictionaryGetResponse\_DictionaryGetResponsePart::class);
        $this->items = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(_Found::class, \Cache_client\_DictionaryGetResponse__Found::class);

