<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client\_ListPopFrontResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cache_client._ListPopFrontResponse._Found</code>
 */
class _Found extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes front = 1;</code>
     */
    protected $front = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $front
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cacheclient::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes front = 1;</code>
     * @return string
     */
    public function getFront()
    {
        return $this->front;
    }

    /**
     * Generated from protobuf field <code>bytes front = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFront($var)
    {
        GPBUtil::checkString($var, False);
        $this->front = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(_Found::class, \Cache_client\_ListPopFrontResponse__Found::class);

