<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vectorindex.proto

namespace Vectorindex;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>vectorindex._GetItemBatchResponse</code>
 */
class _GetItemBatchResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .vectorindex._ItemResponse item_response = 1;</code>
     */
    private $item_response;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Vectorindex\_ItemResponse[]|\Google\Protobuf\Internal\RepeatedField $item_response
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Vectorindex::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .vectorindex._ItemResponse item_response = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItemResponse()
    {
        return $this->item_response;
    }

    /**
     * Generated from protobuf field <code>repeated .vectorindex._ItemResponse item_response = 1;</code>
     * @param \Vectorindex\_ItemResponse[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItemResponse($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Vectorindex\_ItemResponse::class);
        $this->item_response = $arr;

        return $this;
    }

}

