<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vectorindex.proto

namespace Vectorindex;

if (false) {
    /**
     * This class is deprecated. Use Vectorindex\_ItemResponse\_Hit instead.
     * @deprecated
     */
    class _ItemResponse__Hit {}
}
class_exists(_ItemResponse\_Hit::class);
@trigger_error('Vectorindex\_ItemResponse__Hit is deprecated and will be removed in the next major release. Use Vectorindex\_ItemResponse\_Hit instead', E_USER_DEPRECATED);

