<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vectorindex.proto

namespace Vectorindex;

if (false) {
    /**
     * This class is deprecated. Use Vectorindex\_ItemResponse\_Miss instead.
     * @deprecated
     */
    class _ItemResponse__Miss {}
}
class_exists(_ItemResponse\_Miss::class);
@trigger_error('Vectorindex\_ItemResponse__Miss is deprecated and will be removed in the next major release. Use Vectorindex\_ItemResponse\_Miss instead', E_USER_DEPRECATED);

