<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vectorindex.proto

namespace Vectorindex;

if (false) {
    /**
     * This class is deprecated. Use Vectorindex\_ItemMetadataResponse\_Miss instead.
     * @deprecated
     */
    class _ItemMetadataResponse__Miss {}
}
class_exists(_ItemMetadataResponse\_Miss::class);
@trigger_error('Vectorindex\_ItemMetadataResponse__Miss is deprecated and will be removed in the next major release. Use Vectorindex\_ItemMetadataResponse\_Miss instead', E_USER_DEPRECATED);

