<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vectorindex.proto

namespace Vectorindex;

if (false) {
    /**
     * This class is deprecated. Use Vectorindex\_ItemMetadataResponse\_Hit instead.
     * @deprecated
     */
    class _ItemMetadataResponse__Hit {}
}
class_exists(_ItemMetadataResponse\_Hit::class);
@trigger_error('Vectorindex\_ItemMetadataResponse__Hit is deprecated and will be removed in the next major release. Use Vectorindex\_ItemMetadataResponse\_Hit instead', E_USER_DEPRECATED);

