<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vectorindex.proto

namespace Vectorindex;

if (false) {
    /**
     * This class is deprecated. Use Vectorindex\_MetadataRequest\All instead.
     * @deprecated
     */
    class _MetadataRequest_All {}
}
class_exists(_MetadataRequest\All::class);
@trigger_error('Vectorindex\_MetadataRequest_All is deprecated and will be removed in the next major release. Use Vectorindex\_MetadataRequest\All instead', E_USER_DEPRECATED);

