<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vectorindex.proto

namespace Vectorindex;

if (false) {
    /**
     * This class is deprecated. Use Vectorindex\_MetadataRequest\Some instead.
     * @deprecated
     */
    class _MetadataRequest_Some {}
}
class_exists(_MetadataRequest\Some::class);
@trigger_error('Vectorindex\_MetadataRequest_Some is deprecated and will be removed in the next major release. Use Vectorindex\_MetadataRequest\Some instead', E_USER_DEPRECATED);

