<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vectorindex.proto

namespace Vectorindex;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>vectorindex._Metadata</code>
 */
class _Metadata extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string field = 1;</code>
     */
    protected $field = '';
    protected $value;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $field
     *     @type string $string_value
     *     @type int|string $integer_value
     *     @type float $double_value
     *     @type bool $boolean_value
     *     @type \Vectorindex\_Metadata\_ListOfStrings $list_of_strings_value
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Vectorindex::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string field = 1;</code>
     * @return string
     */
    public function getField()
    {
        return $this->field;
    }

    /**
     * Generated from protobuf field <code>string field = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setField($var)
    {
        GPBUtil::checkString($var, True);
        $this->field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string string_value = 2;</code>
     * @return string
     */
    public function getStringValue()
    {
        return $this->readOneof(2);
    }

    public function hasStringValue()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>string string_value = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStringValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 integer_value = 3;</code>
     * @return int|string
     */
    public function getIntegerValue()
    {
        return $this->readOneof(3);
    }

    public function hasIntegerValue()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>int64 integer_value = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIntegerValue($var)
    {
        GPBUtil::checkInt64($var);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>double double_value = 4;</code>
     * @return float
     */
    public function getDoubleValue()
    {
        return $this->readOneof(4);
    }

    public function hasDoubleValue()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>double double_value = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setDoubleValue($var)
    {
        GPBUtil::checkDouble($var);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool boolean_value = 5;</code>
     * @return bool
     */
    public function getBooleanValue()
    {
        return $this->readOneof(5);
    }

    public function hasBooleanValue()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>bool boolean_value = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setBooleanValue($var)
    {
        GPBUtil::checkBool($var);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.vectorindex._Metadata._ListOfStrings list_of_strings_value = 6;</code>
     * @return \Vectorindex\_Metadata\_ListOfStrings|null
     */
    public function getListOfStringsValue()
    {
        return $this->readOneof(6);
    }

    public function hasListOfStringsValue()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>.vectorindex._Metadata._ListOfStrings list_of_strings_value = 6;</code>
     * @param \Vectorindex\_Metadata\_ListOfStrings $var
     * @return $this
     */
    public function setListOfStringsValue($var)
    {
        GPBUtil::checkMessage($var, \Vectorindex\_Metadata\_ListOfStrings::class);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getValue()
    {
        return $this->whichOneof("value");
    }

}

