<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vectorindex.proto

namespace Vectorindex;

if (false) {
    /**
     * This class is deprecated. Use Vectorindex\_Metadata\_ListOfStrings instead.
     * @deprecated
     */
    class _Metadata__ListOfStrings {}
}
class_exists(_Metadata\_ListOfStrings::class);
@trigger_error('Vectorindex\_Metadata__ListOfStrings is deprecated and will be removed in the next major release. Use Vectorindex\_Metadata\_ListOfStrings instead', E_USER_DEPRECATED);

