<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vectorindex.proto

namespace Vectorindex;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>vectorindex._MetadataRequest</code>
 */
class _MetadataRequest extends \Google\Protobuf\Internal\Message
{
    protected $kind;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Vectorindex\_MetadataRequest\Some $some
     *     @type \Vectorindex\_MetadataRequest\All $all
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Vectorindex::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.vectorindex._MetadataRequest.Some some = 2;</code>
     * @return \Vectorindex\_MetadataRequest\Some|null
     */
    public function getSome()
    {
        return $this->readOneof(2);
    }

    public function hasSome()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.vectorindex._MetadataRequest.Some some = 2;</code>
     * @param \Vectorindex\_MetadataRequest\Some $var
     * @return $this
     */
    public function setSome($var)
    {
        GPBUtil::checkMessage($var, \Vectorindex\_MetadataRequest\Some::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.vectorindex._MetadataRequest.All all = 3;</code>
     * @return \Vectorindex\_MetadataRequest\All|null
     */
    public function getAll()
    {
        return $this->readOneof(3);
    }

    public function hasAll()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.vectorindex._MetadataRequest.All all = 3;</code>
     * @param \Vectorindex\_MetadataRequest\All $var
     * @return $this
     */
    public function setAll($var)
    {
        GPBUtil::checkMessage($var, \Vectorindex\_MetadataRequest\All::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getKind()
    {
        return $this->whichOneof("kind");
    }

}

