<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: token.proto

namespace Token;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>token._GenerateDisposableTokenResponse</code>
 */
class _GenerateDisposableTokenResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * the new api key used for authentication against Momento backend
     *
     * Generated from protobuf field <code>string api_key = 1;</code>
     */
    protected $api_key = '';
    /**
     * the Momento endpoint that this token is allowed to make requests against
     *
     * Generated from protobuf field <code>string endpoint = 2;</code>
     */
    protected $endpoint = '';
    /**
     * epoch seconds when the api token expires
     *
     * Generated from protobuf field <code>uint64 valid_until = 3;</code>
     */
    protected $valid_until = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $api_key
     *           the new api key used for authentication against Momento backend
     *     @type string $endpoint
     *           the Momento endpoint that this token is allowed to make requests against
     *     @type int|string $valid_until
     *           epoch seconds when the api token expires
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Token::initOnce();
        parent::__construct($data);
    }

    /**
     * the new api key used for authentication against Momento backend
     *
     * Generated from protobuf field <code>string api_key = 1;</code>
     * @return string
     */
    public function getApiKey()
    {
        return $this->api_key;
    }

    /**
     * the new api key used for authentication against Momento backend
     *
     * Generated from protobuf field <code>string api_key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setApiKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->api_key = $var;

        return $this;
    }

    /**
     * the Momento endpoint that this token is allowed to make requests against
     *
     * Generated from protobuf field <code>string endpoint = 2;</code>
     * @return string
     */
    public function getEndpoint()
    {
        return $this->endpoint;
    }

    /**
     * the Momento endpoint that this token is allowed to make requests against
     *
     * Generated from protobuf field <code>string endpoint = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEndpoint($var)
    {
        GPBUtil::checkString($var, True);
        $this->endpoint = $var;

        return $this;
    }

    /**
     * epoch seconds when the api token expires
     *
     * Generated from protobuf field <code>uint64 valid_until = 3;</code>
     * @return int|string
     */
    public function getValidUntil()
    {
        return $this->valid_until;
    }

    /**
     * epoch seconds when the api token expires
     *
     * Generated from protobuf field <code>uint64 valid_until = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setValidUntil($var)
    {
        GPBUtil::checkUint64($var);
        $this->valid_until = $var;

        return $this;
    }

}

