<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: token.proto

namespace Token;

if (false) {
    /**
     * This class is deprecated. Use Token\_GenerateDisposableTokenRequest\Expires instead.
     * @deprecated
     */
    class _GenerateDisposableTokenRequest_Expires {}
}
class_exists(_GenerateDisposableTokenRequest\Expires::class);
@trigger_error('Token\_GenerateDisposableTokenRequest_Expires is deprecated and will be removed in the next major release. Use Token\_GenerateDisposableTokenRequest\Expires instead', E_USER_DEPRECATED);

