<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permissionmessages.proto

namespace Permission_messages\PermissionsType;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>permission_messages.PermissionsType.CachePermissions</code>
 */
class CachePermissions extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.permission_messages.CacheRole role = 1;</code>
     */
    protected $role = 0;
    protected $cache;
    protected $cache_item;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $role
     *     @type \Permission_messages\PermissionsType\All $all_caches
     *     @type \Permission_messages\PermissionsType\CacheSelector $cache_selector
     *     @type \Permission_messages\PermissionsType\All $all_items
     *     @type \Permission_messages\PermissionsType\CacheItemSelector $item_selector
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Permissionmessages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.permission_messages.CacheRole role = 1;</code>
     * @return int
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * Generated from protobuf field <code>.permission_messages.CacheRole role = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setRole($var)
    {
        GPBUtil::checkEnum($var, \Permission_messages\CacheRole::class);
        $this->role = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.permission_messages.PermissionsType.All all_caches = 2;</code>
     * @return \Permission_messages\PermissionsType\All|null
     */
    public function getAllCaches()
    {
        return $this->readOneof(2);
    }

    public function hasAllCaches()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.permission_messages.PermissionsType.All all_caches = 2;</code>
     * @param \Permission_messages\PermissionsType\All $var
     * @return $this
     */
    public function setAllCaches($var)
    {
        GPBUtil::checkMessage($var, \Permission_messages\PermissionsType\All::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.permission_messages.PermissionsType.CacheSelector cache_selector = 3;</code>
     * @return \Permission_messages\PermissionsType\CacheSelector|null
     */
    public function getCacheSelector()
    {
        return $this->readOneof(3);
    }

    public function hasCacheSelector()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.permission_messages.PermissionsType.CacheSelector cache_selector = 3;</code>
     * @param \Permission_messages\PermissionsType\CacheSelector $var
     * @return $this
     */
    public function setCacheSelector($var)
    {
        GPBUtil::checkMessage($var, \Permission_messages\PermissionsType\CacheSelector::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.permission_messages.PermissionsType.All all_items = 4;</code>
     * @return \Permission_messages\PermissionsType\All|null
     */
    public function getAllItems()
    {
        return $this->readOneof(4);
    }

    public function hasAllItems()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.permission_messages.PermissionsType.All all_items = 4;</code>
     * @param \Permission_messages\PermissionsType\All $var
     * @return $this
     */
    public function setAllItems($var)
    {
        GPBUtil::checkMessage($var, \Permission_messages\PermissionsType\All::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.permission_messages.PermissionsType.CacheItemSelector item_selector = 5;</code>
     * @return \Permission_messages\PermissionsType\CacheItemSelector|null
     */
    public function getItemSelector()
    {
        return $this->readOneof(5);
    }

    public function hasItemSelector()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.permission_messages.PermissionsType.CacheItemSelector item_selector = 5;</code>
     * @param \Permission_messages\PermissionsType\CacheItemSelector $var
     * @return $this
     */
    public function setItemSelector($var)
    {
        GPBUtil::checkMessage($var, \Permission_messages\PermissionsType\CacheItemSelector::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getCache()
    {
        return $this->whichOneof("cache");
    }

    /**
     * @return string
     */
    public function getCacheItem()
    {
        return $this->whichOneof("cache_item");
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(CachePermissions::class, \Permission_messages\PermissionsType_CachePermissions::class);

