<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permissionmessages.proto

namespace Permission_messages\PermissionsType;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>permission_messages.PermissionsType.TopicPermissions</code>
 */
class TopicPermissions extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.permission_messages.TopicRole role = 1;</code>
     */
    protected $role = 0;
    protected $cache;
    protected $topic;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $role
     *     @type \Permission_messages\PermissionsType\All $all_caches
     *     @type \Permission_messages\PermissionsType\CacheSelector $cache_selector
     *     @type \Permission_messages\PermissionsType\All $all_topics
     *     @type \Permission_messages\PermissionsType\TopicSelector $topic_selector
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Permissionmessages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.permission_messages.TopicRole role = 1;</code>
     * @return int
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * Generated from protobuf field <code>.permission_messages.TopicRole role = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setRole($var)
    {
        GPBUtil::checkEnum($var, \Permission_messages\TopicRole::class);
        $this->role = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.permission_messages.PermissionsType.All all_caches = 2;</code>
     * @return \Permission_messages\PermissionsType\All|null
     */
    public function getAllCaches()
    {
        return $this->readOneof(2);
    }

    public function hasAllCaches()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.permission_messages.PermissionsType.All all_caches = 2;</code>
     * @param \Permission_messages\PermissionsType\All $var
     * @return $this
     */
    public function setAllCaches($var)
    {
        GPBUtil::checkMessage($var, \Permission_messages\PermissionsType\All::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.permission_messages.PermissionsType.CacheSelector cache_selector = 3;</code>
     * @return \Permission_messages\PermissionsType\CacheSelector|null
     */
    public function getCacheSelector()
    {
        return $this->readOneof(3);
    }

    public function hasCacheSelector()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.permission_messages.PermissionsType.CacheSelector cache_selector = 3;</code>
     * @param \Permission_messages\PermissionsType\CacheSelector $var
     * @return $this
     */
    public function setCacheSelector($var)
    {
        GPBUtil::checkMessage($var, \Permission_messages\PermissionsType\CacheSelector::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.permission_messages.PermissionsType.All all_topics = 4;</code>
     * @return \Permission_messages\PermissionsType\All|null
     */
    public function getAllTopics()
    {
        return $this->readOneof(4);
    }

    public function hasAllTopics()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.permission_messages.PermissionsType.All all_topics = 4;</code>
     * @param \Permission_messages\PermissionsType\All $var
     * @return $this
     */
    public function setAllTopics($var)
    {
        GPBUtil::checkMessage($var, \Permission_messages\PermissionsType\All::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.permission_messages.PermissionsType.TopicSelector topic_selector = 5;</code>
     * @return \Permission_messages\PermissionsType\TopicSelector|null
     */
    public function getTopicSelector()
    {
        return $this->readOneof(5);
    }

    public function hasTopicSelector()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.permission_messages.PermissionsType.TopicSelector topic_selector = 5;</code>
     * @param \Permission_messages\PermissionsType\TopicSelector $var
     * @return $this
     */
    public function setTopicSelector($var)
    {
        GPBUtil::checkMessage($var, \Permission_messages\PermissionsType\TopicSelector::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getCache()
    {
        return $this->whichOneof("cache");
    }

    /**
     * @return string
     */
    public function getTopic()
    {
        return $this->whichOneof("topic");
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(TopicPermissions::class, \Permission_messages\PermissionsType_TopicPermissions::class);

