<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client\_SortedSetFetchRequest\_ByScore;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cache_client._SortedSetFetchRequest._ByScore._Score</code>
 */
class _Score extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double score = 1;</code>
     */
    protected $score = 0.0;
    /**
     * Generated from protobuf field <code>bool exclusive = 2;</code>
     */
    protected $exclusive = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $score
     *     @type bool $exclusive
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cacheclient::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double score = 1;</code>
     * @return float
     */
    public function getScore()
    {
        return $this->score;
    }

    /**
     * Generated from protobuf field <code>double score = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setScore($var)
    {
        GPBUtil::checkDouble($var);
        $this->score = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool exclusive = 2;</code>
     * @return bool
     */
    public function getExclusive()
    {
        return $this->exclusive;
    }

    /**
     * Generated from protobuf field <code>bool exclusive = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setExclusive($var)
    {
        GPBUtil::checkBool($var);
        $this->exclusive = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(_Score::class, \Cache_client\_SortedSetFetchRequest__ByScore__Score::class);

