<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

namespace Auth\_LoginResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Terminal state, login success
 *
 * Generated from protobuf message <code>auth._LoginResponse.LoggedIn</code>
 */
class LoggedIn extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string session_token = 1;</code>
     */
    protected $session_token = '';
    /**
     * How many seconds the token was valid for when issued.
     * Will vary slightly from reality upon receipt, as
     * time has passed since the token was minted.
     * You might expect to see this true to within 10
     * seconds of client-side timekeeping but as is
     * ever the case, there are no guarantees with
     * public network timing.
     *
     * Generated from protobuf field <code>uint32 valid_for_seconds = 2;</code>
     */
    protected $valid_for_seconds = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $session_token
     *     @type int $valid_for_seconds
     *           How many seconds the token was valid for when issued.
     *           Will vary slightly from reality upon receipt, as
     *           time has passed since the token was minted.
     *           You might expect to see this true to within 10
     *           seconds of client-side timekeeping but as is
     *           ever the case, there are no guarantees with
     *           public network timing.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Auth::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string session_token = 1;</code>
     * @return string
     */
    public function getSessionToken()
    {
        return $this->session_token;
    }

    /**
     * Generated from protobuf field <code>string session_token = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->session_token = $var;

        return $this;
    }

    /**
     * How many seconds the token was valid for when issued.
     * Will vary slightly from reality upon receipt, as
     * time has passed since the token was minted.
     * You might expect to see this true to within 10
     * seconds of client-side timekeeping but as is
     * ever the case, there are no guarantees with
     * public network timing.
     *
     * Generated from protobuf field <code>uint32 valid_for_seconds = 2;</code>
     * @return int
     */
    public function getValidForSeconds()
    {
        return $this->valid_for_seconds;
    }

    /**
     * How many seconds the token was valid for when issued.
     * Will vary slightly from reality upon receipt, as
     * time has passed since the token was minted.
     * You might expect to see this true to within 10
     * seconds of client-side timekeeping but as is
     * ever the case, there are no guarantees with
     * public network timing.
     *
     * Generated from protobuf field <code>uint32 valid_for_seconds = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setValidForSeconds($var)
    {
        GPBUtil::checkUint32($var);
        $this->valid_for_seconds = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(LoggedIn::class, \Auth\_LoginResponse_LoggedIn::class);

