<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client;

if (false) {
    /**
     * This class is deprecated. Use Cache_client\_DictionaryGetResponse\_Missing instead.
     * @deprecated
     */
    class _DictionaryGetResponse__Missing {}
}
class_exists(_DictionaryGetResponse\_Missing::class);
@trigger_error('Cache_client\_DictionaryGetResponse__Missing is deprecated and will be removed in the next major release. Use Cache_client\_DictionaryGetResponse\_Missing instead', E_USER_DEPRECATED);

