<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client;

if (false) {
    /**
     * This class is deprecated. Use Cache_client\_DictionaryDeleteRequest\Some instead.
     * @deprecated
     */
    class _DictionaryDeleteRequest_Some {}
}
class_exists(_DictionaryDeleteRequest\Some::class);
@trigger_error('Cache_client\_DictionaryDeleteRequest_Some is deprecated and will be removed in the next major release. Use Cache_client\_DictionaryDeleteRequest\Some instead', E_USER_DEPRECATED);

