<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cache_client._DictionaryIncrementRequest</code>
 */
class _DictionaryIncrementRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes dictionary_name = 1;</code>
     */
    protected $dictionary_name = '';
    /**
     * Generated from protobuf field <code>bytes field = 2;</code>
     */
    protected $field = '';
    /**
     * Generated from protobuf field <code>int64 amount = 3;</code>
     */
    protected $amount = 0;
    /**
     * Generated from protobuf field <code>uint64 ttl_milliseconds = 4;</code>
     */
    protected $ttl_milliseconds = 0;
    /**
     * Generated from protobuf field <code>bool refresh_ttl = 5;</code>
     */
    protected $refresh_ttl = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $dictionary_name
     *     @type string $field
     *     @type int|string $amount
     *     @type int|string $ttl_milliseconds
     *     @type bool $refresh_ttl
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cacheclient::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes dictionary_name = 1;</code>
     * @return string
     */
    public function getDictionaryName()
    {
        return $this->dictionary_name;
    }

    /**
     * Generated from protobuf field <code>bytes dictionary_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDictionaryName($var)
    {
        GPBUtil::checkString($var, False);
        $this->dictionary_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes field = 2;</code>
     * @return string
     */
    public function getField()
    {
        return $this->field;
    }

    /**
     * Generated from protobuf field <code>bytes field = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setField($var)
    {
        GPBUtil::checkString($var, False);
        $this->field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 amount = 3;</code>
     * @return int|string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>int64 amount = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 ttl_milliseconds = 4;</code>
     * @return int|string
     */
    public function getTtlMilliseconds()
    {
        return $this->ttl_milliseconds;
    }

    /**
     * Generated from protobuf field <code>uint64 ttl_milliseconds = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTtlMilliseconds($var)
    {
        GPBUtil::checkUint64($var);
        $this->ttl_milliseconds = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool refresh_ttl = 5;</code>
     * @return bool
     */
    public function getRefreshTtl()
    {
        return $this->refresh_ttl;
    }

    /**
     * Generated from protobuf field <code>bool refresh_ttl = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setRefreshTtl($var)
    {
        GPBUtil::checkBool($var);
        $this->refresh_ttl = $var;

        return $this;
    }

}

