<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client;

if (false) {
    /**
     * This class is deprecated. Use Cache_client\_DictionaryGetResponse\_Found instead.
     * @deprecated
     */
    class _DictionaryGetResponse__Found {}
}
class_exists(_DictionaryGetResponse\_Found::class);
@trigger_error('Cache_client\_DictionaryGetResponse__Found is deprecated and will be removed in the next major release. Use Cache_client\_DictionaryGetResponse\_Found instead', E_USER_DEPRECATED);

