<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client;

if (false) {
    /**
     * This class is deprecated. Use Cache_client\_DictionaryDeleteRequest\All instead.
     * @deprecated
     */
    class _DictionaryDeleteRequest_All {}
}
class_exists(_DictionaryDeleteRequest\All::class);
@trigger_error('Cache_client\_DictionaryDeleteRequest_All is deprecated and will be removed in the next major release. Use Cache_client\_DictionaryDeleteRequest\All instead', E_USER_DEPRECATED);

