<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client;

if (false) {
    /**
     * This class is deprecated. Use Cache_client\_DictionaryGetResponse\_DictionaryGetResponsePart instead.
     * @deprecated
     */
    class _DictionaryGetResponse__DictionaryGetResponsePart {}
}
class_exists(_DictionaryGetResponse\_DictionaryGetResponsePart::class);
@trigger_error('Cache_client\_DictionaryGetResponse__DictionaryGetResponsePart is deprecated and will be removed in the next major release. Use Cache_client\_DictionaryGetResponse\_DictionaryGetResponsePart instead', E_USER_DEPRECATED);

