<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: httpcache.proto

namespace Cache_client;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cache_client._HttpGetRequest</code>
 */
class _HttpGetRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string cache_name = 1;</code>
     */
    protected $cache_name = '';
    /**
     * Generated from protobuf field <code>string cache_key = 2;</code>
     */
    protected $cache_key = '';
    /**
     * Generated from protobuf field <code>string token = 3;</code>
     */
    protected $token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $cache_name
     *     @type string $cache_key
     *     @type string $token
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Httpcache::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string cache_name = 1;</code>
     * @return string
     */
    public function getCacheName()
    {
        return $this->cache_name;
    }

    /**
     * Generated from protobuf field <code>string cache_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCacheName($var)
    {
        GPBUtil::checkString($var, True);
        $this->cache_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cache_key = 2;</code>
     * @return string
     */
    public function getCacheKey()
    {
        return $this->cache_key;
    }

    /**
     * Generated from protobuf field <code>string cache_key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCacheKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->cache_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string token = 3;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Generated from protobuf field <code>string token = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

}

