<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cache_client._ListConcatenateBackRequest</code>
 */
class _ListConcatenateBackRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes list_name = 1;</code>
     */
    protected $list_name = '';
    /**
     * Generated from protobuf field <code>repeated bytes values = 2;</code>
     */
    private $values;
    /**
     * Generated from protobuf field <code>uint64 ttl_milliseconds = 3;</code>
     */
    protected $ttl_milliseconds = 0;
    /**
     * Generated from protobuf field <code>bool refresh_ttl = 4;</code>
     */
    protected $refresh_ttl = false;
    /**
     * ensure total length <= this; remove excess from front of list
     *
     * Generated from protobuf field <code>uint32 truncate_front_to_size = 5;</code>
     */
    protected $truncate_front_to_size = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $list_name
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $values
     *     @type int|string $ttl_milliseconds
     *     @type bool $refresh_ttl
     *     @type int $truncate_front_to_size
     *           ensure total length <= this; remove excess from front of list
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cacheclient::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes list_name = 1;</code>
     * @return string
     */
    public function getListName()
    {
        return $this->list_name;
    }

    /**
     * Generated from protobuf field <code>bytes list_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setListName($var)
    {
        GPBUtil::checkString($var, False);
        $this->list_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes values = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getValues()
    {
        return $this->values;
    }

    /**
     * Generated from protobuf field <code>repeated bytes values = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setValues($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->values = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 ttl_milliseconds = 3;</code>
     * @return int|string
     */
    public function getTtlMilliseconds()
    {
        return $this->ttl_milliseconds;
    }

    /**
     * Generated from protobuf field <code>uint64 ttl_milliseconds = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTtlMilliseconds($var)
    {
        GPBUtil::checkUint64($var);
        $this->ttl_milliseconds = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool refresh_ttl = 4;</code>
     * @return bool
     */
    public function getRefreshTtl()
    {
        return $this->refresh_ttl;
    }

    /**
     * Generated from protobuf field <code>bool refresh_ttl = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setRefreshTtl($var)
    {
        GPBUtil::checkBool($var);
        $this->refresh_ttl = $var;

        return $this;
    }

    /**
     * ensure total length <= this; remove excess from front of list
     *
     * Generated from protobuf field <code>uint32 truncate_front_to_size = 5;</code>
     * @return int
     */
    public function getTruncateFrontToSize()
    {
        return $this->truncate_front_to_size;
    }

    /**
     * ensure total length <= this; remove excess from front of list
     *
     * Generated from protobuf field <code>uint32 truncate_front_to_size = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setTruncateFrontToSize($var)
    {
        GPBUtil::checkUint32($var);
        $this->truncate_front_to_size = $var;

        return $this;
    }

}

