<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cache_client._ListRange</code>
 */
class _ListRange extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 begin_index = 1;</code>
     */
    protected $begin_index = 0;
    /**
     * Generated from protobuf field <code>uint32 count = 2;</code>
     */
    protected $count = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $begin_index
     *     @type int $count
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cacheclient::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 begin_index = 1;</code>
     * @return int
     */
    public function getBeginIndex()
    {
        return $this->begin_index;
    }

    /**
     * Generated from protobuf field <code>uint32 begin_index = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setBeginIndex($var)
    {
        GPBUtil::checkUint32($var);
        $this->begin_index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 count = 2;</code>
     * @return int
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * Generated from protobuf field <code>uint32 count = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->count = $var;

        return $this;
    }

}

