<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cache_client._ListEraseRequest</code>
 */
class _ListEraseRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes list_name = 1;</code>
     */
    protected $list_name = '';
    protected $erase;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $list_name
     *     @type \Cache_client\_ListEraseRequest\_ListRanges $some
     *     @type \Cache_client\_ListEraseRequest\_All $all
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cacheclient::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes list_name = 1;</code>
     * @return string
     */
    public function getListName()
    {
        return $this->list_name;
    }

    /**
     * Generated from protobuf field <code>bytes list_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setListName($var)
    {
        GPBUtil::checkString($var, False);
        $this->list_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cache_client._ListEraseRequest._ListRanges some = 2;</code>
     * @return \Cache_client\_ListEraseRequest\_ListRanges|null
     */
    public function getSome()
    {
        return $this->readOneof(2);
    }

    public function hasSome()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.cache_client._ListEraseRequest._ListRanges some = 2;</code>
     * @param \Cache_client\_ListEraseRequest\_ListRanges $var
     * @return $this
     */
    public function setSome($var)
    {
        GPBUtil::checkMessage($var, \Cache_client\_ListEraseRequest\_ListRanges::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cache_client._ListEraseRequest._All all = 3;</code>
     * @return \Cache_client\_ListEraseRequest\_All|null
     */
    public function getAll()
    {
        return $this->readOneof(3);
    }

    public function hasAll()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.cache_client._ListEraseRequest._All all = 3;</code>
     * @param \Cache_client\_ListEraseRequest\_All $var
     * @return $this
     */
    public function setAll($var)
    {
        GPBUtil::checkMessage($var, \Cache_client\_ListEraseRequest\_All::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getErase()
    {
        return $this->whichOneof("erase");
    }

}

