<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client;

if (false) {
    /**
     * This class is deprecated. Use Cache_client\_SetIfResponse\_NotStored instead.
     * @deprecated
     */
    class _SetIfResponse__NotStored {}
}
class_exists(_SetIfResponse\_NotStored::class);
@trigger_error('Cache_client\_SetIfResponse__NotStored is deprecated and will be removed in the next major release. Use Cache_client\_SetIfResponse\_NotStored instead', E_USER_DEPRECATED);

