<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client;

if (false) {
    /**
     * This class is deprecated. Use Cache_client\_SetDifferenceRequest\_Minuend instead.
     * @deprecated
     */
    class _SetDifferenceRequest__Minuend {}
}
class_exists(_SetDifferenceRequest\_Minuend::class);
@trigger_error('Cache_client\_SetDifferenceRequest__Minuend is deprecated and will be removed in the next major release. Use Cache_client\_SetDifferenceRequest\_Minuend instead', E_USER_DEPRECATED);

