<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client;

if (false) {
    /**
     * This class is deprecated. Use Cache_client\_SetDifferenceRequest\_Subtrahend instead.
     * @deprecated
     */
    class _SetDifferenceRequest__Subtrahend {}
}
class_exists(_SetDifferenceRequest\_Subtrahend::class);
@trigger_error('Cache_client\_SetDifferenceRequest__Subtrahend is deprecated and will be removed in the next major release. Use Cache_client\_SetDifferenceRequest\_Subtrahend instead', E_USER_DEPRECATED);

