<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client;

if (false) {
    /**
     * This class is deprecated. Use Cache_client\_SetIfNotExistsResponse\_NotStored instead.
     * @deprecated
     */
    class _SetIfNotExistsResponse__NotStored {}
}
class_exists(_SetIfNotExistsResponse\_NotStored::class);
@trigger_error('Cache_client\_SetIfNotExistsResponse__NotStored is deprecated and will be removed in the next major release. Use Cache_client\_SetIfNotExistsResponse\_NotStored instead', E_USER_DEPRECATED);

