<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cache_client._SetUnionRequest</code>
 */
class _SetUnionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes set_name = 1;</code>
     */
    protected $set_name = '';
    /**
     * Generated from protobuf field <code>repeated bytes elements = 2;</code>
     */
    private $elements;
    /**
     * Generated from protobuf field <code>uint64 ttl_milliseconds = 3;</code>
     */
    protected $ttl_milliseconds = 0;
    /**
     * Generated from protobuf field <code>bool refresh_ttl = 4;</code>
     */
    protected $refresh_ttl = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $set_name
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $elements
     *     @type int|string $ttl_milliseconds
     *     @type bool $refresh_ttl
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cacheclient::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes set_name = 1;</code>
     * @return string
     */
    public function getSetName()
    {
        return $this->set_name;
    }

    /**
     * Generated from protobuf field <code>bytes set_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSetName($var)
    {
        GPBUtil::checkString($var, False);
        $this->set_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes elements = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getElements()
    {
        return $this->elements;
    }

    /**
     * Generated from protobuf field <code>repeated bytes elements = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setElements($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->elements = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 ttl_milliseconds = 3;</code>
     * @return int|string
     */
    public function getTtlMilliseconds()
    {
        return $this->ttl_milliseconds;
    }

    /**
     * Generated from protobuf field <code>uint64 ttl_milliseconds = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTtlMilliseconds($var)
    {
        GPBUtil::checkUint64($var);
        $this->ttl_milliseconds = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool refresh_ttl = 4;</code>
     * @return bool
     */
    public function getRefreshTtl()
    {
        return $this->refresh_ttl;
    }

    /**
     * Generated from protobuf field <code>bool refresh_ttl = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setRefreshTtl($var)
    {
        GPBUtil::checkBool($var);
        $this->refresh_ttl = $var;

        return $this;
    }

}

