<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client;

if (false) {
    /**
     * This class is deprecated. Use Cache_client\_SetDifferenceRequest\_Subtrahend\_Set instead.
     * @deprecated
     */
    class _SetDifferenceRequest__Subtrahend__Set {}
}
class_exists(_SetDifferenceRequest\_Subtrahend\_Set::class);
@trigger_error('Cache_client\_SetDifferenceRequest__Subtrahend__Set is deprecated and will be removed in the next major release. Use Cache_client\_SetDifferenceRequest\_Subtrahend\_Set instead', E_USER_DEPRECATED);

