<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client;

if (false) {
    /**
     * This class is deprecated. Use Cache_client\_SetIfResponse\_Stored instead.
     * @deprecated
     */
    class _SetIfResponse__Stored {}
}
class_exists(_SetIfResponse\_Stored::class);
@trigger_error('Cache_client\_SetIfResponse__Stored is deprecated and will be removed in the next major release. Use Cache_client\_SetIfResponse\_Stored instead', E_USER_DEPRECATED);

