<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cache_client._SetIfHashResponse</code>
 */
class _SetIfHashResponse extends \Google\Protobuf\Internal\Message
{
    protected $result;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cache_client\_SetIfHashResponse\_Stored $stored
     *     @type \Cache_client\_SetIfHashResponse\_NotStored $not_stored
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cacheclient::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.cache_client._SetIfHashResponse._Stored stored = 1;</code>
     * @return \Cache_client\_SetIfHashResponse\_Stored|null
     */
    public function getStored()
    {
        return $this->readOneof(1);
    }

    public function hasStored()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.cache_client._SetIfHashResponse._Stored stored = 1;</code>
     * @param \Cache_client\_SetIfHashResponse\_Stored $var
     * @return $this
     */
    public function setStored($var)
    {
        GPBUtil::checkMessage($var, \Cache_client\_SetIfHashResponse\_Stored::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cache_client._SetIfHashResponse._NotStored not_stored = 2;</code>
     * @return \Cache_client\_SetIfHashResponse\_NotStored|null
     */
    public function getNotStored()
    {
        return $this->readOneof(2);
    }

    public function hasNotStored()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.cache_client._SetIfHashResponse._NotStored not_stored = 2;</code>
     * @param \Cache_client\_SetIfHashResponse\_NotStored $var
     * @return $this
     */
    public function setNotStored($var)
    {
        GPBUtil::checkMessage($var, \Cache_client\_SetIfHashResponse\_NotStored::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getResult()
    {
        return $this->whichOneof("result");
    }

}

