<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client;

if (false) {
    /**
     * This class is deprecated. Use Cache_client\_SortedSetFetchResponse\_Found\_Values instead.
     * @deprecated
     */
    class _SortedSetFetchResponse__Found__Values {}
}
class_exists(_SortedSetFetchResponse\_Found\_Values::class);
@trigger_error('Cache_client\_SortedSetFetchResponse__Found__Values is deprecated and will be removed in the next major release. Use Cache_client\_SortedSetFetchResponse\_Found\_Values instead', E_USER_DEPRECATED);

