<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cache_client._SortedSetRemoveRequest</code>
 */
class _SortedSetRemoveRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes set_name = 1;</code>
     */
    protected $set_name = '';
    protected $remove_elements;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $set_name
     *     @type \Cache_client\_SortedSetRemoveRequest\_All $all
     *     @type \Cache_client\_SortedSetRemoveRequest\_Some $some
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cacheclient::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes set_name = 1;</code>
     * @return string
     */
    public function getSetName()
    {
        return $this->set_name;
    }

    /**
     * Generated from protobuf field <code>bytes set_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSetName($var)
    {
        GPBUtil::checkString($var, False);
        $this->set_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cache_client._SortedSetRemoveRequest._All all = 2;</code>
     * @return \Cache_client\_SortedSetRemoveRequest\_All|null
     */
    public function getAll()
    {
        return $this->readOneof(2);
    }

    public function hasAll()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.cache_client._SortedSetRemoveRequest._All all = 2;</code>
     * @param \Cache_client\_SortedSetRemoveRequest\_All $var
     * @return $this
     */
    public function setAll($var)
    {
        GPBUtil::checkMessage($var, \Cache_client\_SortedSetRemoveRequest\_All::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cache_client._SortedSetRemoveRequest._Some some = 3;</code>
     * @return \Cache_client\_SortedSetRemoveRequest\_Some|null
     */
    public function getSome()
    {
        return $this->readOneof(3);
    }

    public function hasSome()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.cache_client._SortedSetRemoveRequest._Some some = 3;</code>
     * @param \Cache_client\_SortedSetRemoveRequest\_Some $var
     * @return $this
     */
    public function setSome($var)
    {
        GPBUtil::checkMessage($var, \Cache_client\_SortedSetRemoveRequest\_Some::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getRemoveElements()
    {
        return $this->whichOneof("remove_elements");
    }

}

