<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client;

if (false) {
    /**
     * This class is deprecated. Use Cache_client\_SortedSetFetchRequest\_ByScore\_Score instead.
     * @deprecated
     */
    class _SortedSetFetchRequest__ByScore__Score {}
}
class_exists(_SortedSetFetchRequest\_ByScore\_Score::class);
@trigger_error('Cache_client\_SortedSetFetchRequest__ByScore__Score is deprecated and will be removed in the next major release. Use Cache_client\_SortedSetFetchRequest\_ByScore\_Score instead', E_USER_DEPRECATED);

