<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client;

if (false) {
    /**
     * This class is deprecated. Use Cache_client\_SortedSetGetRankRequest\Order instead.
     * @deprecated
     */
    class _SortedSetGetRankRequest_Order {}
}
class_exists(_SortedSetGetRankRequest\Order::class);
@trigger_error('Cache_client\_SortedSetGetRankRequest_Order is deprecated and will be removed in the next major release. Use Cache_client\_SortedSetGetRankRequest\Order instead', E_USER_DEPRECATED);

