<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client;

if (false) {
    /**
     * This class is deprecated. Use Cache_client\_SortedSetRemoveRequest\_All instead.
     * @deprecated
     */
    class _SortedSetRemoveRequest__All {}
}
class_exists(_SortedSetRemoveRequest\_All::class);
@trigger_error('Cache_client\_SortedSetRemoveRequest__All is deprecated and will be removed in the next major release. Use Cache_client\_SortedSetRemoveRequest\_All instead', E_USER_DEPRECATED);

