<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client;

if (false) {
    /**
     * This class is deprecated. Use Cache_client\_SortedSetFetchRequest\Order instead.
     * @deprecated
     */
    class _SortedSetFetchRequest_Order {}
}
class_exists(_SortedSetFetchRequest\Order::class);
@trigger_error('Cache_client\_SortedSetFetchRequest_Order is deprecated and will be removed in the next major release. Use Cache_client\_SortedSetFetchRequest\Order instead', E_USER_DEPRECATED);

