<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client;

if (false) {
    /**
     * This class is deprecated. Use Cache_client\_SortedSetFetchRequest\_ByScore instead.
     * @deprecated
     */
    class _SortedSetFetchRequest__ByScore {}
}
class_exists(_SortedSetFetchRequest\_ByScore::class);
@trigger_error('Cache_client\_SortedSetFetchRequest__ByScore is deprecated and will be removed in the next major release. Use Cache_client\_SortedSetFetchRequest\_ByScore instead', E_USER_DEPRECATED);

