<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client;

if (false) {
    /**
     * This class is deprecated. Use Cache_client\_SortedSetRemoveRequest\_Some instead.
     * @deprecated
     */
    class _SortedSetRemoveRequest__Some {}
}
class_exists(_SortedSetRemoveRequest\_Some::class);
@trigger_error('Cache_client\_SortedSetRemoveRequest__Some is deprecated and will be removed in the next major release. Use Cache_client\_SortedSetRemoveRequest\_Some instead', E_USER_DEPRECATED);

