<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cache_client._SortedSetUnionStoreResponse</code>
 */
class _SortedSetUnionStoreResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The number of elements in the destination set after the union.
     * The length is 0 if the result of the union was an empty set.
     *
     * Generated from protobuf field <code>uint32 length = 1;</code>
     */
    protected $length = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $length
     *           The number of elements in the destination set after the union.
     *           The length is 0 if the result of the union was an empty set.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cacheclient::initOnce();
        parent::__construct($data);
    }

    /**
     * The number of elements in the destination set after the union.
     * The length is 0 if the result of the union was an empty set.
     *
     * Generated from protobuf field <code>uint32 length = 1;</code>
     * @return int
     */
    public function getLength()
    {
        return $this->length;
    }

    /**
     * The number of elements in the destination set after the union.
     * The length is 0 if the result of the union was an empty set.
     *
     * Generated from protobuf field <code>uint32 length = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setLength($var)
    {
        GPBUtil::checkUint32($var);
        $this->length = $var;

        return $this;
    }

}

