<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cache_client._SortedSetGetRankRequest</code>
 */
class _SortedSetGetRankRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes set_name = 1;</code>
     */
    protected $set_name = '';
    /**
     * Generated from protobuf field <code>bytes value = 2;</code>
     */
    protected $value = '';
    /**
     * The order in which sorted set will be sorted to determine the rank.
     * When Order.ASCENDING is specified, will return the rank of the value
     * when sorted set scores are ordered from low to high. This is the default
     * when no Order is specified.
     * When Order.DESCENDING is specified, will return the rank of the value
     * when sorted set scores are ordered from high to low.
     *
     * Generated from protobuf field <code>.cache_client._SortedSetGetRankRequest.Order order = 3;</code>
     */
    protected $order = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $set_name
     *     @type string $value
     *     @type int $order
     *           The order in which sorted set will be sorted to determine the rank.
     *           When Order.ASCENDING is specified, will return the rank of the value
     *           when sorted set scores are ordered from low to high. This is the default
     *           when no Order is specified.
     *           When Order.DESCENDING is specified, will return the rank of the value
     *           when sorted set scores are ordered from high to low.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cacheclient::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes set_name = 1;</code>
     * @return string
     */
    public function getSetName()
    {
        return $this->set_name;
    }

    /**
     * Generated from protobuf field <code>bytes set_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSetName($var)
    {
        GPBUtil::checkString($var, False);
        $this->set_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes value = 2;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>bytes value = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->value = $var;

        return $this;
    }

    /**
     * The order in which sorted set will be sorted to determine the rank.
     * When Order.ASCENDING is specified, will return the rank of the value
     * when sorted set scores are ordered from low to high. This is the default
     * when no Order is specified.
     * When Order.DESCENDING is specified, will return the rank of the value
     * when sorted set scores are ordered from high to low.
     *
     * Generated from protobuf field <code>.cache_client._SortedSetGetRankRequest.Order order = 3;</code>
     * @return int
     */
    public function getOrder()
    {
        return $this->order;
    }

    /**
     * The order in which sorted set will be sorted to determine the rank.
     * When Order.ASCENDING is specified, will return the rank of the value
     * when sorted set scores are ordered from low to high. This is the default
     * when no Order is specified.
     * When Order.DESCENDING is specified, will return the rank of the value
     * when sorted set scores are ordered from high to low.
     *
     * Generated from protobuf field <code>.cache_client._SortedSetGetRankRequest.Order order = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setOrder($var)
    {
        GPBUtil::checkEnum($var, \Cache_client\_SortedSetGetRankRequest\Order::class);
        $this->order = $var;

        return $this;
    }

}

