<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client;

if (false) {
    /**
     * This class is deprecated. Use Cache_client\_SortedSetFetchRequest\_ByIndex instead.
     * @deprecated
     */
    class _SortedSetFetchRequest__ByIndex {}
}
class_exists(_SortedSetFetchRequest\_ByIndex::class);
@trigger_error('Cache_client\_SortedSetFetchRequest__ByIndex is deprecated and will be removed in the next major release. Use Cache_client\_SortedSetFetchRequest\_ByIndex instead', E_USER_DEPRECATED);

