<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cache_client._SortedSetFetchRequest</code>
 */
class _SortedSetFetchRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes set_name = 1;</code>
     */
    protected $set_name = '';
    /**
     * Generated from protobuf field <code>.cache_client._SortedSetFetchRequest.Order order = 2;</code>
     */
    protected $order = 0;
    /**
     * Generated from protobuf field <code>bool with_scores = 3;</code>
     */
    protected $with_scores = false;
    protected $range;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $set_name
     *     @type int $order
     *     @type bool $with_scores
     *     @type \Cache_client\_SortedSetFetchRequest\_ByIndex $by_index
     *     @type \Cache_client\_SortedSetFetchRequest\_ByScore $by_score
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cacheclient::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes set_name = 1;</code>
     * @return string
     */
    public function getSetName()
    {
        return $this->set_name;
    }

    /**
     * Generated from protobuf field <code>bytes set_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSetName($var)
    {
        GPBUtil::checkString($var, False);
        $this->set_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cache_client._SortedSetFetchRequest.Order order = 2;</code>
     * @return int
     */
    public function getOrder()
    {
        return $this->order;
    }

    /**
     * Generated from protobuf field <code>.cache_client._SortedSetFetchRequest.Order order = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setOrder($var)
    {
        GPBUtil::checkEnum($var, \Cache_client\_SortedSetFetchRequest\Order::class);
        $this->order = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool with_scores = 3;</code>
     * @return bool
     */
    public function getWithScores()
    {
        return $this->with_scores;
    }

    /**
     * Generated from protobuf field <code>bool with_scores = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setWithScores($var)
    {
        GPBUtil::checkBool($var);
        $this->with_scores = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cache_client._SortedSetFetchRequest._ByIndex by_index = 4;</code>
     * @return \Cache_client\_SortedSetFetchRequest\_ByIndex|null
     */
    public function getByIndex()
    {
        return $this->readOneof(4);
    }

    public function hasByIndex()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.cache_client._SortedSetFetchRequest._ByIndex by_index = 4;</code>
     * @param \Cache_client\_SortedSetFetchRequest\_ByIndex $var
     * @return $this
     */
    public function setByIndex($var)
    {
        GPBUtil::checkMessage($var, \Cache_client\_SortedSetFetchRequest\_ByIndex::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cache_client._SortedSetFetchRequest._ByScore by_score = 5;</code>
     * @return \Cache_client\_SortedSetFetchRequest\_ByScore|null
     */
    public function getByScore()
    {
        return $this->readOneof(5);
    }

    public function hasByScore()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.cache_client._SortedSetFetchRequest._ByScore by_score = 5;</code>
     * @param \Cache_client\_SortedSetFetchRequest\_ByScore $var
     * @return $this
     */
    public function setByScore($var)
    {
        GPBUtil::checkMessage($var, \Cache_client\_SortedSetFetchRequest\_ByScore::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getRange()
    {
        return $this->whichOneof("range");
    }

}

