<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client;

if (false) {
    /**
     * This class is deprecated. Use Cache_client\_SortedSetGetScoreResponse\_SortedSetFound instead.
     * @deprecated
     */
    class _SortedSetGetScoreResponse__SortedSetFound {}
}
class_exists(_SortedSetGetScoreResponse\_SortedSetFound::class);
@trigger_error('Cache_client\_SortedSetGetScoreResponse__SortedSetFound is deprecated and will be removed in the next major release. Use Cache_client\_SortedSetGetScoreResponse\_SortedSetFound instead', E_USER_DEPRECATED);

