<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client;

if (false) {
    /**
     * This class is deprecated. Use Cache_client\_SortedSetGetRankResponse\_SortedSetMissing instead.
     * @deprecated
     */
    class _SortedSetGetRankResponse__SortedSetMissing {}
}
class_exists(_SortedSetGetRankResponse\_SortedSetMissing::class);
@trigger_error('Cache_client\_SortedSetGetRankResponse__SortedSetMissing is deprecated and will be removed in the next major release. Use Cache_client\_SortedSetGetRankResponse\_SortedSetMissing instead', E_USER_DEPRECATED);

