<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client;

if (false) {
    /**
     * This class is deprecated. Use Cache_client\_UpdateTtlResponse\_NotSet instead.
     * @deprecated
     */
    class _UpdateTtlResponse__NotSet {}
}
class_exists(_UpdateTtlResponse\_NotSet::class);
@trigger_error('Cache_client\_UpdateTtlResponse__NotSet is deprecated and will be removed in the next major release. Use Cache_client\_UpdateTtlResponse\_NotSet instead', E_USER_DEPRECATED);

