<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client;

if (false) {
    /**
     * This class is deprecated. Use Cache_client\_UpdateTtlResponse\_Set instead.
     * @deprecated
     */
    class _UpdateTtlResponse__Set {}
}
class_exists(_UpdateTtlResponse\_Set::class);
@trigger_error('Cache_client\_UpdateTtlResponse__Set is deprecated and will be removed in the next major release. Use Cache_client\_UpdateTtlResponse\_Set instead', E_USER_DEPRECATED);

