<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cache_client._UpdateTtlResponse</code>
 */
class _UpdateTtlResponse extends \Google\Protobuf\Internal\Message
{
    protected $result;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cache_client\_UpdateTtlResponse\_Set $set
     *     @type \Cache_client\_UpdateTtlResponse\_NotSet $not_set
     *     @type \Cache_client\_UpdateTtlResponse\_Missing $missing
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cacheclient::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.cache_client._UpdateTtlResponse._Set set = 1;</code>
     * @return \Cache_client\_UpdateTtlResponse\_Set|null
     */
    public function getSet()
    {
        return $this->readOneof(1);
    }

    public function hasSet()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.cache_client._UpdateTtlResponse._Set set = 1;</code>
     * @param \Cache_client\_UpdateTtlResponse\_Set $var
     * @return $this
     */
    public function setSet($var)
    {
        GPBUtil::checkMessage($var, \Cache_client\_UpdateTtlResponse\_Set::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cache_client._UpdateTtlResponse._NotSet not_set = 2;</code>
     * @return \Cache_client\_UpdateTtlResponse\_NotSet|null
     */
    public function getNotSet()
    {
        return $this->readOneof(2);
    }

    public function hasNotSet()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.cache_client._UpdateTtlResponse._NotSet not_set = 2;</code>
     * @param \Cache_client\_UpdateTtlResponse\_NotSet $var
     * @return $this
     */
    public function setNotSet($var)
    {
        GPBUtil::checkMessage($var, \Cache_client\_UpdateTtlResponse\_NotSet::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cache_client._UpdateTtlResponse._Missing missing = 3;</code>
     * @return \Cache_client\_UpdateTtlResponse\_Missing|null
     */
    public function getMissing()
    {
        return $this->readOneof(3);
    }

    public function hasMissing()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.cache_client._UpdateTtlResponse._Missing missing = 3;</code>
     * @param \Cache_client\_UpdateTtlResponse\_Missing $var
     * @return $this
     */
    public function setMissing($var)
    {
        GPBUtil::checkMessage($var, \Cache_client\_UpdateTtlResponse\_Missing::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getResult()
    {
        return $this->whichOneof("result");
    }

}

