<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client;

use UnexpectedValueException;

/**
 * Protobuf type <code>cache_client.ECacheResult</code>
 */
class ECacheResult
{
    /**
     * Generated from protobuf enum <code>Invalid = 0;</code>
     */
    const Invalid = 0;
    /**
     * Generated from protobuf enum <code>Ok = 1;</code>
     */
    const Ok = 1;
    /**
     * Generated from protobuf enum <code>Hit = 2;</code>
     */
    const Hit = 2;
    /**
     * Generated from protobuf enum <code>Miss = 3;</code>
     */
    const Miss = 3;

    private static $valueToName = [
        self::Invalid => 'Invalid',
        self::Ok => 'Ok',
        self::Hit => 'Hit',
        self::Miss => 'Miss',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

