<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cachepubsub.proto

namespace Cache_client\Pubsub;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A message from Momento when we know a subscription to have skipped some messages.
 * We don't terminate your subscription in that case, but just in case you care, we
 * do our best to let you know about it.
 *
 * Generated from protobuf message <code>cache_client.pubsub._Discontinuity</code>
 */
class _Discontinuity extends \Google\Protobuf\Internal\Message
{
    /**
     * The last topic value sequence number known to have been attempted (if known, 0 otherwise).
     *
     * Generated from protobuf field <code>uint64 last_topic_sequence = 1;</code>
     */
    protected $last_topic_sequence = 0;
    /**
     * The new topic sequence number after which TopicItems will ostensibly resume.
     *
     * Generated from protobuf field <code>uint64 new_topic_sequence = 2;</code>
     */
    protected $new_topic_sequence = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $last_topic_sequence
     *           The last topic value sequence number known to have been attempted (if known, 0 otherwise).
     *     @type int|string $new_topic_sequence
     *           The new topic sequence number after which TopicItems will ostensibly resume.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cachepubsub::initOnce();
        parent::__construct($data);
    }

    /**
     * The last topic value sequence number known to have been attempted (if known, 0 otherwise).
     *
     * Generated from protobuf field <code>uint64 last_topic_sequence = 1;</code>
     * @return int|string
     */
    public function getLastTopicSequence()
    {
        return $this->last_topic_sequence;
    }

    /**
     * The last topic value sequence number known to have been attempted (if known, 0 otherwise).
     *
     * Generated from protobuf field <code>uint64 last_topic_sequence = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLastTopicSequence($var)
    {
        GPBUtil::checkUint64($var);
        $this->last_topic_sequence = $var;

        return $this;
    }

    /**
     * The new topic sequence number after which TopicItems will ostensibly resume.
     *
     * Generated from protobuf field <code>uint64 new_topic_sequence = 2;</code>
     * @return int|string
     */
    public function getNewTopicSequence()
    {
        return $this->new_topic_sequence;
    }

    /**
     * The new topic sequence number after which TopicItems will ostensibly resume.
     *
     * Generated from protobuf field <code>uint64 new_topic_sequence = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNewTopicSequence($var)
    {
        GPBUtil::checkUint64($var);
        $this->new_topic_sequence = $var;

        return $this;
    }

}

