<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cachepubsub.proto

namespace Cache_client\Pubsub;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Your subscription has yielded an item you previously published. Here it is!
 *
 * Generated from protobuf message <code>cache_client.pubsub._TopicItem</code>
 */
class _TopicItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Topic sequence numbers give an order of messages per-topic.
     * All subscribers to a topic will receive messages in the same order, with the same sequence numbers.
     *
     * Generated from protobuf field <code>uint64 topic_sequence_number = 1;</code>
     */
    protected $topic_sequence_number = 0;
    /**
     * The value you previously published to this topic.
     *
     * Generated from protobuf field <code>.cache_client.pubsub._TopicValue value = 2;</code>
     */
    protected $value = null;
    /**
     * Authenticated id from Publisher's disposable token
     *
     * Generated from protobuf field <code>string publisher_id = 3;</code>
     */
    protected $publisher_id = '';
    /**
     * Sequence pages exist to determine which sequence number range a message belongs to. On a topic reset,
     * the sequence numbers reset and a new sequence_page is given.
     * For a given sequence_page, the next message in a topic is topic_sequence_number + 1.
     * Later sequence pages are numbered greater than earlier pages, but they don't go one-by-one.
     *
     * Generated from protobuf field <code>uint64 sequence_page = 4;</code>
     */
    protected $sequence_page = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $topic_sequence_number
     *           Topic sequence numbers give an order of messages per-topic.
     *           All subscribers to a topic will receive messages in the same order, with the same sequence numbers.
     *     @type \Cache_client\Pubsub\_TopicValue $value
     *           The value you previously published to this topic.
     *     @type string $publisher_id
     *           Authenticated id from Publisher's disposable token
     *     @type int|string $sequence_page
     *           Sequence pages exist to determine which sequence number range a message belongs to. On a topic reset,
     *           the sequence numbers reset and a new sequence_page is given.
     *           For a given sequence_page, the next message in a topic is topic_sequence_number + 1.
     *           Later sequence pages are numbered greater than earlier pages, but they don't go one-by-one.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cachepubsub::initOnce();
        parent::__construct($data);
    }

    /**
     * Topic sequence numbers give an order of messages per-topic.
     * All subscribers to a topic will receive messages in the same order, with the same sequence numbers.
     *
     * Generated from protobuf field <code>uint64 topic_sequence_number = 1;</code>
     * @return int|string
     */
    public function getTopicSequenceNumber()
    {
        return $this->topic_sequence_number;
    }

    /**
     * Topic sequence numbers give an order of messages per-topic.
     * All subscribers to a topic will receive messages in the same order, with the same sequence numbers.
     *
     * Generated from protobuf field <code>uint64 topic_sequence_number = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTopicSequenceNumber($var)
    {
        GPBUtil::checkUint64($var);
        $this->topic_sequence_number = $var;

        return $this;
    }

    /**
     * The value you previously published to this topic.
     *
     * Generated from protobuf field <code>.cache_client.pubsub._TopicValue value = 2;</code>
     * @return \Cache_client\Pubsub\_TopicValue|null
     */
    public function getValue()
    {
        return $this->value;
    }

    public function hasValue()
    {
        return isset($this->value);
    }

    public function clearValue()
    {
        unset($this->value);
    }

    /**
     * The value you previously published to this topic.
     *
     * Generated from protobuf field <code>.cache_client.pubsub._TopicValue value = 2;</code>
     * @param \Cache_client\Pubsub\_TopicValue $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkMessage($var, \Cache_client\Pubsub\_TopicValue::class);
        $this->value = $var;

        return $this;
    }

    /**
     * Authenticated id from Publisher's disposable token
     *
     * Generated from protobuf field <code>string publisher_id = 3;</code>
     * @return string
     */
    public function getPublisherId()
    {
        return $this->publisher_id;
    }

    /**
     * Authenticated id from Publisher's disposable token
     *
     * Generated from protobuf field <code>string publisher_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPublisherId($var)
    {
        GPBUtil::checkString($var, True);
        $this->publisher_id = $var;

        return $this;
    }

    /**
     * Sequence pages exist to determine which sequence number range a message belongs to. On a topic reset,
     * the sequence numbers reset and a new sequence_page is given.
     * For a given sequence_page, the next message in a topic is topic_sequence_number + 1.
     * Later sequence pages are numbered greater than earlier pages, but they don't go one-by-one.
     *
     * Generated from protobuf field <code>uint64 sequence_page = 4;</code>
     * @return int|string
     */
    public function getSequencePage()
    {
        return $this->sequence_page;
    }

    /**
     * Sequence pages exist to determine which sequence number range a message belongs to. On a topic reset,
     * the sequence numbers reset and a new sequence_page is given.
     * For a given sequence_page, the next message in a topic is topic_sequence_number + 1.
     * Later sequence pages are numbered greater than earlier pages, but they don't go one-by-one.
     *
     * Generated from protobuf field <code>uint64 sequence_page = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSequencePage($var)
    {
        GPBUtil::checkUint64($var);
        $this->sequence_page = $var;

        return $this;
    }

}

