<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cachepubsub.proto

namespace Cache_client\Pubsub;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Your subscription has yielded an item you previously published. Here it is!
 *
 * Generated from protobuf message <code>cache_client.pubsub._TopicItem</code>
 */
class _TopicItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Topic sequence numbers are **best-effort** and **informational**.
     * They are not transactional.
     * They exist:
     * * to help reconnect to an existing topic while trying to avoid missing items.
     * * to facilitate richer monitoring and logging.
     * * to provide a best-effort awareness of stream contiguity, or lack thereof,
     *   in case you need to know.
     * You can safely ignore them if none of that matters to you!
     *
     * Generated from protobuf field <code>uint64 topic_sequence_number = 1;</code>
     */
    protected $topic_sequence_number = 0;
    /**
     * The value you previously published to this topic.
     *
     * Generated from protobuf field <code>.cache_client.pubsub._TopicValue value = 2;</code>
     */
    protected $value = null;
    /**
     * Authenticated id from Publisher's disposable token
     *
     * Generated from protobuf field <code>string publisher_id = 3;</code>
     */
    protected $publisher_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $topic_sequence_number
     *           Topic sequence numbers are **best-effort** and **informational**.
     *           They are not transactional.
     *           They exist:
     *           * to help reconnect to an existing topic while trying to avoid missing items.
     *           * to facilitate richer monitoring and logging.
     *           * to provide a best-effort awareness of stream contiguity, or lack thereof,
     *             in case you need to know.
     *           You can safely ignore them if none of that matters to you!
     *     @type \Cache_client\Pubsub\_TopicValue $value
     *           The value you previously published to this topic.
     *     @type string $publisher_id
     *           Authenticated id from Publisher's disposable token
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cachepubsub::initOnce();
        parent::__construct($data);
    }

    /**
     * Topic sequence numbers are **best-effort** and **informational**.
     * They are not transactional.
     * They exist:
     * * to help reconnect to an existing topic while trying to avoid missing items.
     * * to facilitate richer monitoring and logging.
     * * to provide a best-effort awareness of stream contiguity, or lack thereof,
     *   in case you need to know.
     * You can safely ignore them if none of that matters to you!
     *
     * Generated from protobuf field <code>uint64 topic_sequence_number = 1;</code>
     * @return int|string
     */
    public function getTopicSequenceNumber()
    {
        return $this->topic_sequence_number;
    }

    /**
     * Topic sequence numbers are **best-effort** and **informational**.
     * They are not transactional.
     * They exist:
     * * to help reconnect to an existing topic while trying to avoid missing items.
     * * to facilitate richer monitoring and logging.
     * * to provide a best-effort awareness of stream contiguity, or lack thereof,
     *   in case you need to know.
     * You can safely ignore them if none of that matters to you!
     *
     * Generated from protobuf field <code>uint64 topic_sequence_number = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTopicSequenceNumber($var)
    {
        GPBUtil::checkUint64($var);
        $this->topic_sequence_number = $var;

        return $this;
    }

    /**
     * The value you previously published to this topic.
     *
     * Generated from protobuf field <code>.cache_client.pubsub._TopicValue value = 2;</code>
     * @return \Cache_client\Pubsub\_TopicValue|null
     */
    public function getValue()
    {
        return $this->value;
    }

    public function hasValue()
    {
        return isset($this->value);
    }

    public function clearValue()
    {
        unset($this->value);
    }

    /**
     * The value you previously published to this topic.
     *
     * Generated from protobuf field <code>.cache_client.pubsub._TopicValue value = 2;</code>
     * @param \Cache_client\Pubsub\_TopicValue $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkMessage($var, \Cache_client\Pubsub\_TopicValue::class);
        $this->value = $var;

        return $this;
    }

    /**
     * Authenticated id from Publisher's disposable token
     *
     * Generated from protobuf field <code>string publisher_id = 3;</code>
     * @return string
     */
    public function getPublisherId()
    {
        return $this->publisher_id;
    }

    /**
     * Authenticated id from Publisher's disposable token
     *
     * Generated from protobuf field <code>string publisher_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPublisherId($var)
    {
        GPBUtil::checkString($var, True);
        $this->publisher_id = $var;

        return $this;
    }

}

