<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client\_SetIfHashResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cache_client._SetIfHashResponse._Stored</code>
 */
class _Stored extends \Google\Protobuf\Internal\Message
{
    /**
     * Hash computed on the newly stored value
     *
     * Generated from protobuf field <code>bytes new_hash = 1;</code>
     */
    protected $new_hash = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $new_hash
     *           Hash computed on the newly stored value
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cacheclient::initOnce();
        parent::__construct($data);
    }

    /**
     * Hash computed on the newly stored value
     *
     * Generated from protobuf field <code>bytes new_hash = 1;</code>
     * @return string
     */
    public function getNewHash()
    {
        return $this->new_hash;
    }

    /**
     * Hash computed on the newly stored value
     *
     * Generated from protobuf field <code>bytes new_hash = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setNewHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->new_hash = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(_Stored::class, \Cache_client\_SetIfHashResponse__Stored::class);

