<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client\_SortedSetGetScoreResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cache_client._SortedSetGetScoreResponse._SortedSetFound</code>
 */
class _SortedSetFound extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .cache_client._SortedSetGetScoreResponse._SortedSetGetScoreResponsePart elements = 1;</code>
     */
    private $elements;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cache_client\_SortedSetGetScoreResponse\_SortedSetGetScoreResponsePart[]|\Google\Protobuf\Internal\RepeatedField $elements
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cacheclient::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .cache_client._SortedSetGetScoreResponse._SortedSetGetScoreResponsePart elements = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getElements()
    {
        return $this->elements;
    }

    /**
     * Generated from protobuf field <code>repeated .cache_client._SortedSetGetScoreResponse._SortedSetGetScoreResponsePart elements = 1;</code>
     * @param \Cache_client\_SortedSetGetScoreResponse\_SortedSetGetScoreResponsePart[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setElements($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cache_client\_SortedSetGetScoreResponse\_SortedSetGetScoreResponsePart::class);
        $this->elements = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(_SortedSetFound::class, \Cache_client\_SortedSetGetScoreResponse__SortedSetFound::class);

