<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client\_SortedSetGetScoreResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cache_client._SortedSetGetScoreResponse._SortedSetGetScoreResponsePart</code>
 */
class _SortedSetGetScoreResponsePart extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.cache_client.ECacheResult result = 1;</code>
     */
    protected $result = 0;
    /**
     * Generated from protobuf field <code>double score = 2;</code>
     */
    protected $score = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $result
     *     @type float $score
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cacheclient::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.cache_client.ECacheResult result = 1;</code>
     * @return int
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * Generated from protobuf field <code>.cache_client.ECacheResult result = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkEnum($var, \Cache_client\ECacheResult::class);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double score = 2;</code>
     * @return float
     */
    public function getScore()
    {
        return $this->score;
    }

    /**
     * Generated from protobuf field <code>double score = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setScore($var)
    {
        GPBUtil::checkDouble($var);
        $this->score = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(_SortedSetGetScoreResponsePart::class, \Cache_client\_SortedSetGetScoreResponse__SortedSetGetScoreResponsePart::class);

