<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client\_SortedSetGetRankResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cache_client._SortedSetGetRankResponse._RankResponsePart</code>
 */
class _RankResponsePart extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.cache_client.ECacheResult result = 1;</code>
     */
    protected $result = 0;
    /**
     * Rank is 0-based i.e. when sort order is descending the rank of the
     * value with the highest score will be 0. Similarly for ascending order,
     * value with the lowest score will have rank 0.
     *
     * Generated from protobuf field <code>uint64 rank = 2;</code>
     */
    protected $rank = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $result
     *     @type int|string $rank
     *           Rank is 0-based i.e. when sort order is descending the rank of the
     *           value with the highest score will be 0. Similarly for ascending order,
     *           value with the lowest score will have rank 0.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cacheclient::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.cache_client.ECacheResult result = 1;</code>
     * @return int
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * Generated from protobuf field <code>.cache_client.ECacheResult result = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkEnum($var, \Cache_client\ECacheResult::class);
        $this->result = $var;

        return $this;
    }

    /**
     * Rank is 0-based i.e. when sort order is descending the rank of the
     * value with the highest score will be 0. Similarly for ascending order,
     * value with the lowest score will have rank 0.
     *
     * Generated from protobuf field <code>uint64 rank = 2;</code>
     * @return int|string
     */
    public function getRank()
    {
        return $this->rank;
    }

    /**
     * Rank is 0-based i.e. when sort order is descending the rank of the
     * value with the highest score will be 0. Similarly for ascending order,
     * value with the lowest score will have rank 0.
     *
     * Generated from protobuf field <code>uint64 rank = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRank($var)
    {
        GPBUtil::checkUint64($var);
        $this->rank = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(_RankResponsePart::class, \Cache_client\_SortedSetGetRankResponse__RankResponsePart::class);

