<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client\_ListRetainResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cache_client._ListRetainResponse._Found</code>
 */
class _Found extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 list_length = 1;</code>
     */
    protected $list_length = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $list_length
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cacheclient::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 list_length = 1;</code>
     * @return int
     */
    public function getListLength()
    {
        return $this->list_length;
    }

    /**
     * Generated from protobuf field <code>uint32 list_length = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setListLength($var)
    {
        GPBUtil::checkUint32($var);
        $this->list_length = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(_Found::class, \Cache_client\_ListRetainResponse__Found::class);

