<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

namespace Auth\_GenerateApiTokenRequest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>auth._GenerateApiTokenRequest.ExplicitPermissions</code>
 */
class ExplicitPermissions extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .auth._GenerateApiTokenRequest.PermissionsType permissions = 1;</code>
     */
    private $permissions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Auth\_GenerateApiTokenRequest\PermissionsType[]|\Google\Protobuf\Internal\RepeatedField $permissions
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Auth::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .auth._GenerateApiTokenRequest.PermissionsType permissions = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPermissions()
    {
        return $this->permissions;
    }

    /**
     * Generated from protobuf field <code>repeated .auth._GenerateApiTokenRequest.PermissionsType permissions = 1;</code>
     * @param \Auth\_GenerateApiTokenRequest\PermissionsType[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPermissions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Auth\_GenerateApiTokenRequest\PermissionsType::class);
        $this->permissions = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ExplicitPermissions::class, \Auth\_GenerateApiTokenRequest_ExplicitPermissions::class);

