<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

namespace Auth\_GenerateApiTokenRequest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>auth._GenerateApiTokenRequest.Permissions</code>
 */
class Permissions extends \Google\Protobuf\Internal\Message
{
    protected $kind;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $super_user
     *     @type \Auth\_GenerateApiTokenRequest\ExplicitPermissions $explicit
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Auth::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.auth._GenerateApiTokenRequest.SuperUserPermissions super_user = 1;</code>
     * @return int
     */
    public function getSuperUser()
    {
        return $this->readOneof(1);
    }

    public function hasSuperUser()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.auth._GenerateApiTokenRequest.SuperUserPermissions super_user = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSuperUser($var)
    {
        GPBUtil::checkEnum($var, \Auth\_GenerateApiTokenRequest\SuperUserPermissions::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.auth._GenerateApiTokenRequest.ExplicitPermissions explicit = 2;</code>
     * @return \Auth\_GenerateApiTokenRequest\ExplicitPermissions|null
     */
    public function getExplicit()
    {
        return $this->readOneof(2);
    }

    public function hasExplicit()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.auth._GenerateApiTokenRequest.ExplicitPermissions explicit = 2;</code>
     * @param \Auth\_GenerateApiTokenRequest\ExplicitPermissions $var
     * @return $this
     */
    public function setExplicit($var)
    {
        GPBUtil::checkMessage($var, \Auth\_GenerateApiTokenRequest\ExplicitPermissions::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getKind()
    {
        return $this->whichOneof("kind");
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Permissions::class, \Auth\_GenerateApiTokenRequest_Permissions::class);

