<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: leaderboard.proto

namespace Leaderboard;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Leaderboards are made up of many of these.
 *
 * Generated from protobuf message <code>leaderboard._Element</code>
 */
class _Element extends \Google\Protobuf\Internal\Message
{
    /**
     * A player identifier, session identifier, browser identifier or whatever other kind of
     * identifier you use for this scoreboard. The full unsigned 64 bit range is allowed here,
     * between 0 and 2^63-1 inclusive.
     * An id can only appear in a leaderboard one time. You can't have 2 scores for 1 player,
     * unless that player has 2 ids!
     *
     * Generated from protobuf field <code>uint32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * The value by which this element is sorted within the leaderboard.
     *
     * Generated from protobuf field <code>double score = 3;</code>
     */
    protected $score = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *           A player identifier, session identifier, browser identifier or whatever other kind of
     *           identifier you use for this scoreboard. The full unsigned 64 bit range is allowed here,
     *           between 0 and 2^63-1 inclusive.
     *           An id can only appear in a leaderboard one time. You can't have 2 scores for 1 player,
     *           unless that player has 2 ids!
     *     @type float $score
     *           The value by which this element is sorted within the leaderboard.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Leaderboard::initOnce();
        parent::__construct($data);
    }

    /**
     * A player identifier, session identifier, browser identifier or whatever other kind of
     * identifier you use for this scoreboard. The full unsigned 64 bit range is allowed here,
     * between 0 and 2^63-1 inclusive.
     * An id can only appear in a leaderboard one time. You can't have 2 scores for 1 player,
     * unless that player has 2 ids!
     *
     * Generated from protobuf field <code>uint32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * A player identifier, session identifier, browser identifier or whatever other kind of
     * identifier you use for this scoreboard. The full unsigned 64 bit range is allowed here,
     * between 0 and 2^63-1 inclusive.
     * An id can only appear in a leaderboard one time. You can't have 2 scores for 1 player,
     * unless that player has 2 ids!
     *
     * Generated from protobuf field <code>uint32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * The value by which this element is sorted within the leaderboard.
     *
     * Generated from protobuf field <code>double score = 3;</code>
     * @return float
     */
    public function getScore()
    {
        return $this->score;
    }

    /**
     * The value by which this element is sorted within the leaderboard.
     *
     * Generated from protobuf field <code>double score = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setScore($var)
    {
        GPBUtil::checkDouble($var);
        $this->score = $var;

        return $this;
    }

}

