<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: leaderboard.proto

namespace Leaderboard;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>leaderboard._GetCompetitionRankRequest</code>
 */
class _GetCompetitionRankRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string leaderboard = 1;</code>
     */
    protected $leaderboard = '';
    /**
     * Generated from protobuf field <code>repeated uint32 ids = 2;</code>
     */
    private $ids;
    /**
     * If not specified, the order is descending.
     *
     * Generated from protobuf field <code>optional .leaderboard._Order order = 3;</code>
     */
    protected $order = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $leaderboard
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $ids
     *     @type int $order
     *           If not specified, the order is descending.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Leaderboard::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string leaderboard = 1;</code>
     * @return string
     */
    public function getLeaderboard()
    {
        return $this->leaderboard;
    }

    /**
     * Generated from protobuf field <code>string leaderboard = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLeaderboard($var)
    {
        GPBUtil::checkString($var, True);
        $this->leaderboard = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 ids = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIds()
    {
        return $this->ids;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 ids = 2;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->ids = $arr;

        return $this;
    }

    /**
     * If not specified, the order is descending.
     *
     * Generated from protobuf field <code>optional .leaderboard._Order order = 3;</code>
     * @return int
     */
    public function getOrder()
    {
        return isset($this->order) ? $this->order : 0;
    }

    public function hasOrder()
    {
        return isset($this->order);
    }

    public function clearOrder()
    {
        unset($this->order);
    }

    /**
     * If not specified, the order is descending.
     *
     * Generated from protobuf field <code>optional .leaderboard._Order order = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setOrder($var)
    {
        GPBUtil::checkEnum($var, \Leaderboard\_Order::class);
        $this->order = $var;

        return $this;
    }

}

