<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: leaderboard.proto

namespace Leaderboard;

use UnexpectedValueException;

/**
 * Protobuf type <code>leaderboard._Order</code>
 */
class _Order
{
    /**
     * Ascending order (0 is the lowest-scoring rank)
     *
     * Generated from protobuf enum <code>ASCENDING = 0;</code>
     */
    const ASCENDING = 0;
    /**
     * Descending order (0 is the highest-scoring rank)
     *
     * Generated from protobuf enum <code>DESCENDING = 1;</code>
     */
    const DESCENDING = 1;

    private static $valueToName = [
        self::ASCENDING => 'ASCENDING',
        self::DESCENDING => 'DESCENDING',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

