<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: leaderboard.proto

namespace Leaderboard;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Query APIs using RankRange expect a limit of 8192 elements. Requesting a range wider than
 * that is expected to return an error.
 * RankRange models half-open ranges: 0..4 refers to elements 0, 1, 2 and 3.
 * Example permissible ranges:
 * * 0..8192
 * * 1..8193
 * * 123..8315
 * * 0..1
 * * 1..4
 * * 13..17
 * Example error ranges:
 * * 0..0
 * * 4..3
 * * 0..8193
 *
 * Generated from protobuf message <code>leaderboard._RankRange</code>
 */
class _RankRange extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 start_inclusive = 1;</code>
     */
    protected $start_inclusive = 0;
    /**
     * Generated from protobuf field <code>uint32 end_exclusive = 2;</code>
     */
    protected $end_exclusive = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $start_inclusive
     *     @type int $end_exclusive
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Leaderboard::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 start_inclusive = 1;</code>
     * @return int
     */
    public function getStartInclusive()
    {
        return $this->start_inclusive;
    }

    /**
     * Generated from protobuf field <code>uint32 start_inclusive = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setStartInclusive($var)
    {
        GPBUtil::checkUint32($var);
        $this->start_inclusive = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 end_exclusive = 2;</code>
     * @return int
     */
    public function getEndExclusive()
    {
        return $this->end_exclusive;
    }

    /**
     * Generated from protobuf field <code>uint32 end_exclusive = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setEndExclusive($var)
    {
        GPBUtil::checkUint32($var);
        $this->end_exclusive = $var;

        return $this;
    }

}

