<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto

namespace Store;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * This response is for when a get request concludes successfully.
 * These are some of the Errors and their corresponding GRPC status codes.
 * 1. Invalid argument was provided, value is missing -> grpc code = INVALID_ARGUMENT.  Metadata: "err" -> "momento_general_err"
 * 2. Item does not exist. grpc code = NOT_FOUND. Metadata: "err" -> "item_not_found"
 * 3. Store not found. grpc code = NOT_FOUND. Metadata: "err" -> "store_not_found"
 *
 * Generated from protobuf message <code>store._StoreGetResponse</code>
 */
class _StoreGetResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.store._StoreValue value = 1;</code>
     */
    protected $value = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Store\_StoreValue $value
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Store::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.store._StoreValue value = 1;</code>
     * @return \Store\_StoreValue|null
     */
    public function getValue()
    {
        return $this->value;
    }

    public function hasValue()
    {
        return isset($this->value);
    }

    public function clearValue()
    {
        unset($this->value);
    }

    /**
     * Generated from protobuf field <code>.store._StoreValue value = 1;</code>
     * @param \Store\_StoreValue $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkMessage($var, \Store\_StoreValue::class);
        $this->value = $var;

        return $this;
    }

}

