<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: httpcache.proto

namespace GPBMetadata;

class Httpcache
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Cacheclient::initOnce();
        \GPBMetadata\Google\Api\Httpbody::initOnce();
        \GPBMetadata\Google\Api\Annotations::initOnce();
        $pool->internalAddGeneratedFile(
            '
¯
httpcache.protocache_clientgoogle/api/httpbody.protogoogle/api/annotations.proto"G
_HttpGetRequest

cache_name (	
	cache_key (	
token (	"ã
_HttpSetRequest

cache_name (	
	cache_key (	
ttl_milliseconds (
token (	(

cache_body (2.google.api.HttpBody2ı
	HttpCacheg
Get.cache_client._HttpGetRequest.google.api.HttpBody"+Ç”‰ì%#/cache/get/{cache_name}/{cache_key}y
Set.cache_client._HttpSetRequest.cache_client._SetResponse"7Ç”‰ì1"#/cache/set/{cache_name}/{cache_key}:
cache_bodyÉ
SetButItsAPut.cache_client._HttpSetRequest.cache_client._SetResponse"7Ç”‰ì1#/cache/set/{cache_name}/{cache_key}:
cache_bodyBG
grpc.cache_clientPZ0github.com/momentohq/client-sdk-go;client_sdk_gobproto3'
        , true);

        static::$is_initialized = true;
    }
}

