<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

namespace Auth\_GenerateApiTokenRequest\PermissionsType;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>auth._GenerateApiTokenRequest.PermissionsType.TopicPermissions</code>
 */
class TopicPermissions extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.auth._GenerateApiTokenRequest.TopicRole role = 1;</code>
     */
    protected $role = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $role
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Auth::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.auth._GenerateApiTokenRequest.TopicRole role = 1;</code>
     * @return int
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * Generated from protobuf field <code>.auth._GenerateApiTokenRequest.TopicRole role = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setRole($var)
    {
        GPBUtil::checkEnum($var, \Auth\_GenerateApiTokenRequest\TopicRole::class);
        $this->role = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(TopicPermissions::class, \Auth\_GenerateApiTokenRequest_PermissionsType_TopicPermissions::class);

