<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permissionmessages.proto

namespace Permission_messages;

if (false) {
    /**
     * This class is deprecated. Use Permission_messages\PermissionsType\CacheSelector instead.
     * @deprecated
     */
    class PermissionsType_CacheSelector {}
}
class_exists(PermissionsType\CacheSelector::class);
@trigger_error('Permission_messages\PermissionsType_CacheSelector is deprecated and will be removed in the next major release. Use Permission_messages\PermissionsType\CacheSelector instead', E_USER_DEPRECATED);

