<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permissionmessages.proto

namespace Permission_messages;

if (false) {
    /**
     * This class is deprecated. Use Permission_messages\PermissionsType\CacheItemSelector instead.
     * @deprecated
     */
    class PermissionsType_CacheItemSelector {}
}
class_exists(PermissionsType\CacheItemSelector::class);
@trigger_error('Permission_messages\PermissionsType_CacheItemSelector is deprecated and will be removed in the next major release. Use Permission_messages\PermissionsType\CacheItemSelector instead', E_USER_DEPRECATED);

