<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permissionmessages.proto

namespace Permission_messages;

if (false) {
    /**
     * This class is deprecated. Use Permission_messages\PermissionsType\TopicSelector instead.
     * @deprecated
     */
    class PermissionsType_TopicSelector {}
}
class_exists(PermissionsType\TopicSelector::class);
@trigger_error('Permission_messages\PermissionsType_TopicSelector is deprecated and will be removed in the next major release. Use Permission_messages\PermissionsType\TopicSelector instead', E_USER_DEPRECATED);

