<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permissionmessages.proto

namespace Permission_messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>permission_messages.Permissions</code>
 */
class Permissions extends \Google\Protobuf\Internal\Message
{
    protected $kind;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $super_user
     *     @type \Permission_messages\ExplicitPermissions $explicit
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Permissionmessages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.permission_messages.SuperUserPermissions super_user = 1;</code>
     * @return int
     */
    public function getSuperUser()
    {
        return $this->readOneof(1);
    }

    public function hasSuperUser()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.permission_messages.SuperUserPermissions super_user = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSuperUser($var)
    {
        GPBUtil::checkEnum($var, \Permission_messages\SuperUserPermissions::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.permission_messages.ExplicitPermissions explicit = 2;</code>
     * @return \Permission_messages\ExplicitPermissions|null
     */
    public function getExplicit()
    {
        return $this->readOneof(2);
    }

    public function hasExplicit()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.permission_messages.ExplicitPermissions explicit = 2;</code>
     * @param \Permission_messages\ExplicitPermissions $var
     * @return $this
     */
    public function setExplicit($var)
    {
        GPBUtil::checkMessage($var, \Permission_messages\ExplicitPermissions::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getKind()
    {
        return $this->whichOneof("kind");
    }

}

