<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permissionmessages.proto

namespace Permission_messages;

if (false) {
    /**
     * This class is deprecated. Use Permission_messages\PermissionsType\CachePermissions instead.
     * @deprecated
     */
    class PermissionsType_CachePermissions {}
}
class_exists(PermissionsType\CachePermissions::class);
@trigger_error('Permission_messages\PermissionsType_CachePermissions is deprecated and will be removed in the next major release. Use Permission_messages\PermissionsType\CachePermissions instead', E_USER_DEPRECATED);

