<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permissionmessages.proto

namespace Permission_messages;

use UnexpectedValueException;

/**
 * Protobuf type <code>permission_messages.SuperUserPermissions</code>
 */
class SuperUserPermissions
{
    /**
     * Generated from protobuf enum <code>SuperUser = 0;</code>
     */
    const SuperUser = 0;

    private static $valueToName = [
        self::SuperUser => 'SuperUser',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

