<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client\_SortedSetUnionStoreRequest;

use UnexpectedValueException;

/**
 * Protobuf type <code>cache_client._SortedSetUnionStoreRequest.AggregateFunction</code>
 */
class AggregateFunction
{
    /**
     * Sum the weighted scores of an element across all the source sets. This is the default.
     *
     * Generated from protobuf enum <code>SUM = 0;</code>
     */
    const SUM = 0;
    /**
     * Use the minimum of the weight scores of an element across all the source sets.
     *
     * Generated from protobuf enum <code>MIN = 1;</code>
     */
    const MIN = 1;
    /**
     * Use the maximum of the weight scores of an element across all the source sets.
     *
     * Generated from protobuf enum <code>MAX = 2;</code>
     */
    const MAX = 2;

    private static $valueToName = [
        self::SUM => 'SUM',
        self::MIN => 'MIN',
        self::MAX => 'MAX',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(AggregateFunction::class, \Cache_client\_SortedSetUnionStoreRequest_AggregateFunction::class);

