<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client\_ListEraseRequest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cache_client._ListEraseRequest._ListRanges</code>
 */
class _ListRanges extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .cache_client._ListRange ranges = 1;</code>
     */
    private $ranges;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cache_client\_ListRange[]|\Google\Protobuf\Internal\RepeatedField $ranges
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cacheclient::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .cache_client._ListRange ranges = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRanges()
    {
        return $this->ranges;
    }

    /**
     * Generated from protobuf field <code>repeated .cache_client._ListRange ranges = 1;</code>
     * @param \Cache_client\_ListRange[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRanges($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cache_client\_ListRange::class);
        $this->ranges = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(_ListRanges::class, \Cache_client\_ListEraseRequest__ListRanges::class);

