<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

namespace Auth;

if (false) {
    /**
     * This class is deprecated. Use Auth\_GenerateApiTokenRequest\Expires instead.
     * @deprecated
     */
    class _GenerateApiTokenRequest_Expires {}
}
class_exists(_GenerateApiTokenRequest\Expires::class);
@trigger_error('Auth\_GenerateApiTokenRequest_Expires is deprecated and will be removed in the next major release. Use Auth\_GenerateApiTokenRequest\Expires instead', E_USER_DEPRECATED);

