<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

namespace Auth;

if (false) {
    /**
     * This class is deprecated. Use Auth\_GenerateApiTokenRequest\Never instead.
     * @deprecated
     */
    class _GenerateApiTokenRequest_Never {}
}
class_exists(_GenerateApiTokenRequest\Never::class);
@trigger_error('Auth\_GenerateApiTokenRequest_Never is deprecated and will be removed in the next major release. Use Auth\_GenerateApiTokenRequest\Never instead', E_USER_DEPRECATED);

