<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

namespace Auth;

if (false) {
    /**
     * This class is deprecated. Use Auth\_GenerateApiTokenRequest\Permissions instead.
     * @deprecated
     */
    class _GenerateApiTokenRequest_Permissions {}
}
class_exists(_GenerateApiTokenRequest\Permissions::class);
@trigger_error('Auth\_GenerateApiTokenRequest_Permissions is deprecated and will be removed in the next major release. Use Auth\_GenerateApiTokenRequest\Permissions instead', E_USER_DEPRECATED);

