<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

namespace Auth;

if (false) {
    /**
     * This class is deprecated. Use Auth\_GenerateApiTokenRequest\CacheRole instead.
     * @deprecated
     */
    class _GenerateApiTokenRequest_CacheRole {}
}
class_exists(_GenerateApiTokenRequest\CacheRole::class);
@trigger_error('Auth\_GenerateApiTokenRequest_CacheRole is deprecated and will be removed in the next major release. Use Auth\_GenerateApiTokenRequest\CacheRole instead', E_USER_DEPRECATED);

