<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

namespace Auth;

if (false) {
    /**
     * This class is deprecated. Use Auth\_GenerateApiTokenRequest\SuperUserPermissions instead.
     * @deprecated
     */
    class _GenerateApiTokenRequest_SuperUserPermissions {}
}
class_exists(_GenerateApiTokenRequest\SuperUserPermissions::class);
@trigger_error('Auth\_GenerateApiTokenRequest_SuperUserPermissions is deprecated and will be removed in the next major release. Use Auth\_GenerateApiTokenRequest\SuperUserPermissions instead', E_USER_DEPRECATED);

