<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

namespace Auth;

if (false) {
    /**
     * This class is deprecated. Use Auth\_GenerateApiTokenRequest\PermissionsType\CachePermissions instead.
     * @deprecated
     */
    class _GenerateApiTokenRequest_PermissionsType_CachePermissions {}
}
class_exists(_GenerateApiTokenRequest\PermissionsType\CachePermissions::class);
@trigger_error('Auth\_GenerateApiTokenRequest_PermissionsType_CachePermissions is deprecated and will be removed in the next major release. Use Auth\_GenerateApiTokenRequest\PermissionsType\CachePermissions instead', E_USER_DEPRECATED);

