<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

namespace Auth;

if (false) {
    /**
     * This class is deprecated. Use Auth\_GenerateApiTokenRequest\PermissionsType instead.
     * @deprecated
     */
    class _GenerateApiTokenRequest_PermissionsType {}
}
class_exists(_GenerateApiTokenRequest\PermissionsType::class);
@trigger_error('Auth\_GenerateApiTokenRequest_PermissionsType is deprecated and will be removed in the next major release. Use Auth\_GenerateApiTokenRequest\PermissionsType instead', E_USER_DEPRECATED);

