<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

namespace Auth;

if (false) {
    /**
     * This class is deprecated. Use Auth\_LoginResponse\Message instead.
     * @deprecated
     */
    class _LoginResponse_Message {}
}
class_exists(_LoginResponse\Message::class);
@trigger_error('Auth\_LoginResponse_Message is deprecated and will be removed in the next major release. Use Auth\_LoginResponse\Message instead', E_USER_DEPRECATED);

