<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

namespace Auth;

if (false) {
    /**
     * This class is deprecated. Use Auth\_LoginResponse\DirectBrowser instead.
     * @deprecated
     */
    class _LoginResponse_DirectBrowser {}
}
class_exists(_LoginResponse\DirectBrowser::class);
@trigger_error('Auth\_LoginResponse_DirectBrowser is deprecated and will be removed in the next major release. Use Auth\_LoginResponse\DirectBrowser instead', E_USER_DEPRECATED);

