<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

namespace Auth;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>auth._LoginResponse</code>
 */
class _LoginResponse extends \Google\Protobuf\Internal\Message
{
    protected $state;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Auth\_LoginResponse\DirectBrowser $direct_browser
     *     @type \Auth\_LoginResponse\LoggedIn $logged_in
     *     @type \Auth\_LoginResponse\Message $message
     *     @type \Auth\_LoginResponse\Error $error
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Auth::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.auth._LoginResponse.DirectBrowser direct_browser = 1;</code>
     * @return \Auth\_LoginResponse\DirectBrowser|null
     */
    public function getDirectBrowser()
    {
        return $this->readOneof(1);
    }

    public function hasDirectBrowser()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.auth._LoginResponse.DirectBrowser direct_browser = 1;</code>
     * @param \Auth\_LoginResponse\DirectBrowser $var
     * @return $this
     */
    public function setDirectBrowser($var)
    {
        GPBUtil::checkMessage($var, \Auth\_LoginResponse\DirectBrowser::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.auth._LoginResponse.LoggedIn logged_in = 2;</code>
     * @return \Auth\_LoginResponse\LoggedIn|null
     */
    public function getLoggedIn()
    {
        return $this->readOneof(2);
    }

    public function hasLoggedIn()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.auth._LoginResponse.LoggedIn logged_in = 2;</code>
     * @param \Auth\_LoginResponse\LoggedIn $var
     * @return $this
     */
    public function setLoggedIn($var)
    {
        GPBUtil::checkMessage($var, \Auth\_LoginResponse\LoggedIn::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.auth._LoginResponse.Message message = 3;</code>
     * @return \Auth\_LoginResponse\Message|null
     */
    public function getMessage()
    {
        return $this->readOneof(3);
    }

    public function hasMessage()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.auth._LoginResponse.Message message = 3;</code>
     * @param \Auth\_LoginResponse\Message $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkMessage($var, \Auth\_LoginResponse\Message::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.auth._LoginResponse.Error error = 4;</code>
     * @return \Auth\_LoginResponse\Error|null
     */
    public function getError()
    {
        return $this->readOneof(4);
    }

    public function hasError()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.auth._LoginResponse.Error error = 4;</code>
     * @param \Auth\_LoginResponse\Error $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkMessage($var, \Auth\_LoginResponse\Error::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getState()
    {
        return $this->whichOneof("state");
    }

}

