<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

namespace Auth;

if (false) {
    /**
     * This class is deprecated. Use Auth\_LoginResponse\Error instead.
     * @deprecated
     */
    class _LoginResponse_Error {}
}
class_exists(_LoginResponse\Error::class);
@trigger_error('Auth\_LoginResponse_Error is deprecated and will be removed in the next major release. Use Auth\_LoginResponse\Error instead', E_USER_DEPRECATED);

