<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

namespace Auth;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>auth._RefreshApiTokenRequest</code>
 */
class _RefreshApiTokenRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * the existing api token to be refreshed
     *
     * Generated from protobuf field <code>string api_key = 1;</code>
     */
    protected $api_key = '';
    /**
     * the refresh token that was generated with that api token
     *
     * Generated from protobuf field <code>string refresh_token = 2;</code>
     */
    protected $refresh_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $api_key
     *           the existing api token to be refreshed
     *     @type string $refresh_token
     *           the refresh token that was generated with that api token
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Auth::initOnce();
        parent::__construct($data);
    }

    /**
     * the existing api token to be refreshed
     *
     * Generated from protobuf field <code>string api_key = 1;</code>
     * @return string
     */
    public function getApiKey()
    {
        return $this->api_key;
    }

    /**
     * the existing api token to be refreshed
     *
     * Generated from protobuf field <code>string api_key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setApiKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->api_key = $var;

        return $this;
    }

    /**
     * the refresh token that was generated with that api token
     *
     * Generated from protobuf field <code>string refresh_token = 2;</code>
     * @return string
     */
    public function getRefreshToken()
    {
        return $this->refresh_token;
    }

    /**
     * the refresh token that was generated with that api token
     *
     * Generated from protobuf field <code>string refresh_token = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRefreshToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->refresh_token = $var;

        return $this;
    }

}

