<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>common.NotEqual</code>
 */
class NotEqual extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes value_to_check = 1;</code>
     */
    protected $value_to_check = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $value_to_check
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes value_to_check = 1;</code>
     * @return string
     */
    public function getValueToCheck()
    {
        return $this->value_to_check;
    }

    /**
     * Generated from protobuf field <code>bytes value_to_check = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setValueToCheck($var)
    {
        GPBUtil::checkString($var, False);
        $this->value_to_check = $var;

        return $this;
    }

}

