<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: controlclient.proto

namespace Control_client;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>control_client._Cache</code>
 */
class _Cache extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string cache_name = 1;</code>
     */
    protected $cache_name = '';
    /**
     * Generated from protobuf field <code>.control_client._CacheLimits cache_limits = 2;</code>
     */
    protected $cache_limits = null;
    /**
     * Generated from protobuf field <code>.control_client._TopicLimits topic_limits = 3;</code>
     */
    protected $topic_limits = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $cache_name
     *     @type \Control_client\_CacheLimits $cache_limits
     *     @type \Control_client\_TopicLimits $topic_limits
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Controlclient::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string cache_name = 1;</code>
     * @return string
     */
    public function getCacheName()
    {
        return $this->cache_name;
    }

    /**
     * Generated from protobuf field <code>string cache_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCacheName($var)
    {
        GPBUtil::checkString($var, True);
        $this->cache_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.control_client._CacheLimits cache_limits = 2;</code>
     * @return \Control_client\_CacheLimits|null
     */
    public function getCacheLimits()
    {
        return $this->cache_limits;
    }

    public function hasCacheLimits()
    {
        return isset($this->cache_limits);
    }

    public function clearCacheLimits()
    {
        unset($this->cache_limits);
    }

    /**
     * Generated from protobuf field <code>.control_client._CacheLimits cache_limits = 2;</code>
     * @param \Control_client\_CacheLimits $var
     * @return $this
     */
    public function setCacheLimits($var)
    {
        GPBUtil::checkMessage($var, \Control_client\_CacheLimits::class);
        $this->cache_limits = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.control_client._TopicLimits topic_limits = 3;</code>
     * @return \Control_client\_TopicLimits|null
     */
    public function getTopicLimits()
    {
        return $this->topic_limits;
    }

    public function hasTopicLimits()
    {
        return isset($this->topic_limits);
    }

    public function clearTopicLimits()
    {
        unset($this->topic_limits);
    }

    /**
     * Generated from protobuf field <code>.control_client._TopicLimits topic_limits = 3;</code>
     * @param \Control_client\_TopicLimits $var
     * @return $this
     */
    public function setTopicLimits($var)
    {
        GPBUtil::checkMessage($var, \Control_client\_TopicLimits::class);
        $this->topic_limits = $var;

        return $this;
    }

}

