<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: controlclient.proto

namespace Control_client;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>control_client._CacheLimits</code>
 */
class _CacheLimits extends \Google\Protobuf\Internal\Message
{
    /**
     * The amount of transactions per second that can be exercised
     *
     * Generated from protobuf field <code>uint32 max_traffic_rate = 1;</code>
     */
    protected $max_traffic_rate = 0;
    /**
     * The amount of traffic per second that can be exercised in KiB
     *
     * Generated from protobuf field <code>uint32 max_throughput_kbps = 2;</code>
     */
    protected $max_throughput_kbps = 0;
    /**
     * The maximum size of a single item in KiB
     *
     * Generated from protobuf field <code>uint32 max_item_size_kb = 3;</code>
     */
    protected $max_item_size_kb = 0;
    /**
     * The maximum TTL allowed for a single item, in seconds
     *
     * Generated from protobuf field <code>uint64 max_ttl_seconds = 4;</code>
     */
    protected $max_ttl_seconds = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $max_traffic_rate
     *           The amount of transactions per second that can be exercised
     *     @type int $max_throughput_kbps
     *           The amount of traffic per second that can be exercised in KiB
     *     @type int $max_item_size_kb
     *           The maximum size of a single item in KiB
     *     @type int|string $max_ttl_seconds
     *           The maximum TTL allowed for a single item, in seconds
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Controlclient::initOnce();
        parent::__construct($data);
    }

    /**
     * The amount of transactions per second that can be exercised
     *
     * Generated from protobuf field <code>uint32 max_traffic_rate = 1;</code>
     * @return int
     */
    public function getMaxTrafficRate()
    {
        return $this->max_traffic_rate;
    }

    /**
     * The amount of transactions per second that can be exercised
     *
     * Generated from protobuf field <code>uint32 max_traffic_rate = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxTrafficRate($var)
    {
        GPBUtil::checkUint32($var);
        $this->max_traffic_rate = $var;

        return $this;
    }

    /**
     * The amount of traffic per second that can be exercised in KiB
     *
     * Generated from protobuf field <code>uint32 max_throughput_kbps = 2;</code>
     * @return int
     */
    public function getMaxThroughputKbps()
    {
        return $this->max_throughput_kbps;
    }

    /**
     * The amount of traffic per second that can be exercised in KiB
     *
     * Generated from protobuf field <code>uint32 max_throughput_kbps = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxThroughputKbps($var)
    {
        GPBUtil::checkUint32($var);
        $this->max_throughput_kbps = $var;

        return $this;
    }

    /**
     * The maximum size of a single item in KiB
     *
     * Generated from protobuf field <code>uint32 max_item_size_kb = 3;</code>
     * @return int
     */
    public function getMaxItemSizeKb()
    {
        return $this->max_item_size_kb;
    }

    /**
     * The maximum size of a single item in KiB
     *
     * Generated from protobuf field <code>uint32 max_item_size_kb = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxItemSizeKb($var)
    {
        GPBUtil::checkUint32($var);
        $this->max_item_size_kb = $var;

        return $this;
    }

    /**
     * The maximum TTL allowed for a single item, in seconds
     *
     * Generated from protobuf field <code>uint64 max_ttl_seconds = 4;</code>
     * @return int|string
     */
    public function getMaxTtlSeconds()
    {
        return $this->max_ttl_seconds;
    }

    /**
     * The maximum TTL allowed for a single item, in seconds
     *
     * Generated from protobuf field <code>uint64 max_ttl_seconds = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaxTtlSeconds($var)
    {
        GPBUtil::checkUint64($var);
        $this->max_ttl_seconds = $var;

        return $this;
    }

}

