<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: controlclient.proto

namespace Control_client;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>control_client._CreateSigningKeyResponse</code>
 */
class _CreateSigningKeyResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string key = 1;</code>
     */
    protected $key = '';
    /**
     * Generated from protobuf field <code>uint64 expires_at = 2;</code>
     */
    protected $expires_at = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $key
     *     @type int|string $expires_at
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Controlclient::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string key = 1;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>string key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 expires_at = 2;</code>
     * @return int|string
     */
    public function getExpiresAt()
    {
        return $this->expires_at;
    }

    /**
     * Generated from protobuf field <code>uint64 expires_at = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpiresAt($var)
    {
        GPBUtil::checkUint64($var);
        $this->expires_at = $var;

        return $this;
    }

}

