<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: controlclient.proto

namespace Control_client;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>control_client._CreateIndexRequest</code>
 */
class _CreateIndexRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string index_name = 1;</code>
     */
    protected $index_name = '';
    /**
     * Generated from protobuf field <code>uint64 num_dimensions = 2;</code>
     */
    protected $num_dimensions = 0;
    /**
     * Generated from protobuf field <code>.control_client._SimilarityMetric similarity_metric = 3;</code>
     */
    protected $similarity_metric = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $index_name
     *     @type int|string $num_dimensions
     *     @type \Control_client\_SimilarityMetric $similarity_metric
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Controlclient::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string index_name = 1;</code>
     * @return string
     */
    public function getIndexName()
    {
        return $this->index_name;
    }

    /**
     * Generated from protobuf field <code>string index_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setIndexName($var)
    {
        GPBUtil::checkString($var, True);
        $this->index_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 num_dimensions = 2;</code>
     * @return int|string
     */
    public function getNumDimensions()
    {
        return $this->num_dimensions;
    }

    /**
     * Generated from protobuf field <code>uint64 num_dimensions = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNumDimensions($var)
    {
        GPBUtil::checkUint64($var);
        $this->num_dimensions = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.control_client._SimilarityMetric similarity_metric = 3;</code>
     * @return \Control_client\_SimilarityMetric|null
     */
    public function getSimilarityMetric()
    {
        return $this->similarity_metric;
    }

    public function hasSimilarityMetric()
    {
        return isset($this->similarity_metric);
    }

    public function clearSimilarityMetric()
    {
        unset($this->similarity_metric);
    }

    /**
     * Generated from protobuf field <code>.control_client._SimilarityMetric similarity_metric = 3;</code>
     * @param \Control_client\_SimilarityMetric $var
     * @return $this
     */
    public function setSimilarityMetric($var)
    {
        GPBUtil::checkMessage($var, \Control_client\_SimilarityMetric::class);
        $this->similarity_metric = $var;

        return $this;
    }

}

