<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: controlclient.proto

namespace Control_client;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>control_client._CreateSigningKeyRequest</code>
 */
class _CreateSigningKeyRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 ttl_minutes = 1;</code>
     */
    protected $ttl_minutes = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $ttl_minutes
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Controlclient::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 ttl_minutes = 1;</code>
     * @return int
     */
    public function getTtlMinutes()
    {
        return $this->ttl_minutes;
    }

    /**
     * Generated from protobuf field <code>uint32 ttl_minutes = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTtlMinutes($var)
    {
        GPBUtil::checkUint32($var);
        $this->ttl_minutes = $var;

        return $this;
    }

}

