<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: controlclient.proto

namespace Control_client;

if (false) {
    /**
     * This class is deprecated. Use Control_client\_GenerateApiTokenRequest\Never instead.
     * @deprecated
     */
    class _GenerateApiTokenRequest_Never {}
}
class_exists(_GenerateApiTokenRequest\Never::class);
@trigger_error('Control_client\_GenerateApiTokenRequest_Never is deprecated and will be removed in the next major release. Use Control_client\_GenerateApiTokenRequest\Never instead', E_USER_DEPRECATED);

