<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: controlclient.proto

namespace Control_client;

if (false) {
    /**
     * This class is deprecated. Use Control_client\_GenerateApiTokenRequest\Expires instead.
     * @deprecated
     */
    class _GenerateApiTokenRequest_Expires {}
}
class_exists(_GenerateApiTokenRequest\Expires::class);
@trigger_error('Control_client\_GenerateApiTokenRequest_Expires is deprecated and will be removed in the next major release. Use Control_client\_GenerateApiTokenRequest\Expires instead', E_USER_DEPRECATED);

