<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: controlclient.proto

namespace Control_client;

if (false) {
    /**
     * This class is deprecated. Use Control_client\_ListIndexesResponse\_Index instead.
     * @deprecated
     */
    class _ListIndexesResponse__Index {}
}
class_exists(_ListIndexesResponse\_Index::class);
@trigger_error('Control_client\_ListIndexesResponse__Index is deprecated and will be removed in the next major release. Use Control_client\_ListIndexesResponse\_Index instead', E_USER_DEPRECATED);

