<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: controlclient.proto

namespace Control_client;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>control_client._ListIndexesResponse</code>
 */
class _ListIndexesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .control_client._ListIndexesResponse._Index indexes = 1;</code>
     */
    private $indexes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Control_client\_ListIndexesResponse\_Index[]|\Google\Protobuf\Internal\RepeatedField $indexes
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Controlclient::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .control_client._ListIndexesResponse._Index indexes = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIndexes()
    {
        return $this->indexes;
    }

    /**
     * Generated from protobuf field <code>repeated .control_client._ListIndexesResponse._Index indexes = 1;</code>
     * @param \Control_client\_ListIndexesResponse\_Index[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIndexes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Control_client\_ListIndexesResponse\_Index::class);
        $this->indexes = $arr;

        return $this;
    }

}

