<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: controlclient.proto

namespace Control_client;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>control_client._ListCachesResponse</code>
 */
class _ListCachesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .control_client._Cache cache = 1;</code>
     */
    private $cache;
    /**
     * Generated from protobuf field <code>string next_token = 2;</code>
     */
    protected $next_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Control_client\_Cache[]|\Google\Protobuf\Internal\RepeatedField $cache
     *     @type string $next_token
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Controlclient::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .control_client._Cache cache = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCache()
    {
        return $this->cache;
    }

    /**
     * Generated from protobuf field <code>repeated .control_client._Cache cache = 1;</code>
     * @param \Control_client\_Cache[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCache($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Control_client\_Cache::class);
        $this->cache = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string next_token = 2;</code>
     * @return string
     */
    public function getNextToken()
    {
        return $this->next_token;
    }

    /**
     * Generated from protobuf field <code>string next_token = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNextToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->next_token = $var;

        return $this;
    }

}

