<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: controlclient.proto

namespace Control_client;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>control_client._SigningKey</code>
 */
class _SigningKey extends \Google\Protobuf\Internal\Message
{
    /**
     * The id of the signing key
     *
     * Generated from protobuf field <code>string key_id = 1;</code>
     */
    protected $key_id = '';
    /**
     * Epoch time in seconds when the signing key expires
     *
     * Generated from protobuf field <code>uint64 expires_at = 2;</code>
     */
    protected $expires_at = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $key_id
     *           The id of the signing key
     *     @type int|string $expires_at
     *           Epoch time in seconds when the signing key expires
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Controlclient::initOnce();
        parent::__construct($data);
    }

    /**
     * The id of the signing key
     *
     * Generated from protobuf field <code>string key_id = 1;</code>
     * @return string
     */
    public function getKeyId()
    {
        return $this->key_id;
    }

    /**
     * The id of the signing key
     *
     * Generated from protobuf field <code>string key_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKeyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->key_id = $var;

        return $this;
    }

    /**
     * Epoch time in seconds when the signing key expires
     *
     * Generated from protobuf field <code>uint64 expires_at = 2;</code>
     * @return int|string
     */
    public function getExpiresAt()
    {
        return $this->expires_at;
    }

    /**
     * Epoch time in seconds when the signing key expires
     *
     * Generated from protobuf field <code>uint64 expires_at = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpiresAt($var)
    {
        GPBUtil::checkUint64($var);
        $this->expires_at = $var;

        return $this;
    }

}

