<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: controlclient.proto

namespace Control_client;

if (false) {
    /**
     * This class is deprecated. Use Control_client\_SimilarityMetric\_InnerProduct instead.
     * @deprecated
     */
    class _SimilarityMetric__InnerProduct {}
}
class_exists(_SimilarityMetric\_InnerProduct::class);
@trigger_error('Control_client\_SimilarityMetric__InnerProduct is deprecated and will be removed in the next major release. Use Control_client\_SimilarityMetric\_InnerProduct instead', E_USER_DEPRECATED);

