<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: webhook.proto

namespace Webhook;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>webhook._DeleteWebhookRequest</code>
 */
class _DeleteWebhookRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.webhook._WebhookId webhook_id = 1;</code>
     */
    protected $webhook_id = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Webhook\_WebhookId $webhook_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Webhook::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.webhook._WebhookId webhook_id = 1;</code>
     * @return \Webhook\_WebhookId|null
     */
    public function getWebhookId()
    {
        return $this->webhook_id;
    }

    public function hasWebhookId()
    {
        return isset($this->webhook_id);
    }

    public function clearWebhookId()
    {
        unset($this->webhook_id);
    }

    /**
     * Generated from protobuf field <code>.webhook._WebhookId webhook_id = 1;</code>
     * @param \Webhook\_WebhookId $var
     * @return $this
     */
    public function setWebhookId($var)
    {
        GPBUtil::checkMessage($var, \Webhook\_WebhookId::class);
        $this->webhook_id = $var;

        return $this;
    }

}

