<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: webhook.proto

namespace Webhook;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>webhook._ListWebhooksResponse</code>
 */
class _ListWebhooksResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .webhook._Webhook webhook = 1;</code>
     */
    private $webhook;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Webhook\_Webhook[]|\Google\Protobuf\Internal\RepeatedField $webhook
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Webhook::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .webhook._Webhook webhook = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getWebhook()
    {
        return $this->webhook;
    }

    /**
     * Generated from protobuf field <code>repeated .webhook._Webhook webhook = 1;</code>
     * @param \Webhook\_Webhook[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setWebhook($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Webhook\_Webhook::class);
        $this->webhook = $arr;

        return $this;
    }

}

