<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: webhook.proto

namespace Webhook;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>webhook._PutWebhookRequest</code>
 */
class _PutWebhookRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.webhook._Webhook webhook = 1;</code>
     */
    protected $webhook = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Webhook\_Webhook $webhook
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Webhook::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.webhook._Webhook webhook = 1;</code>
     * @return \Webhook\_Webhook|null
     */
    public function getWebhook()
    {
        return $this->webhook;
    }

    public function hasWebhook()
    {
        return isset($this->webhook);
    }

    public function clearWebhook()
    {
        unset($this->webhook);
    }

    /**
     * Generated from protobuf field <code>.webhook._Webhook webhook = 1;</code>
     * @param \Webhook\_Webhook $var
     * @return $this
     */
    public function setWebhook($var)
    {
        GPBUtil::checkMessage($var, \Webhook\_Webhook::class);
        $this->webhook = $var;

        return $this;
    }

}

