<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: webhook.proto

namespace Webhook;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>webhook._WebhookDestination</code>
 */
class _WebhookDestination extends \Google\Protobuf\Internal\Message
{
    protected $kind;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $post_url
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Webhook::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string post_url = 1;</code>
     * @return string
     */
    public function getPostUrl()
    {
        return $this->readOneof(1);
    }

    public function hasPostUrl()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>string post_url = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPostUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getKind()
    {
        return $this->whichOneof("kind");
    }

}

