<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheclient.proto

namespace Cache_client\_SortedSetFetchRequest;

use UnexpectedValueException;

/**
 * Protobuf type <code>cache_client._SortedSetFetchRequest.Order</code>
 */
class Order
{
    /**
     * Generated from protobuf enum <code>ASCENDING = 0;</code>
     */
    const ASCENDING = 0;
    /**
     * Generated from protobuf enum <code>DESCENDING = 1;</code>
     */
    const DESCENDING = 1;

    private static $valueToName = [
        self::ASCENDING => 'ASCENDING',
        self::DESCENDING => 'DESCENDING',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Order::class, \Cache_client\_SortedSetFetchRequest_Order::class);

