name: On push to main

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MOMENTO_API_KEY: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.MOMENTO_MACHINE_USER_GITHUB_TOKEN }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: grpc, protobuf
          tools: composer

      - name: Install dependencies
        run: composer install

      - name: Run tests
        run: php vendor/phpunit/phpunit/phpunit --configuration phpunit.xml

      - name: Run examples
        env:
          MOMENTO_API_KEY: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}
        working-directory: ./examples
        run: |
          composer install
          php ./example.php
          php ./dictionary-example.php
          php ./list-example.php
          php ./set-example.php
          php ./doc-examples-php-apis.php
          php ./storage-example.php
          php ./psr16-example.php

      - name: Generate README
        uses: momentohq/standards-and-practices/github-actions/generate-and-commit-oss-readme@gh-actions-v2
        with:
          project_status: official
          project_stability: stable
          project_type: sdk
          sdk_language: PHP
          dev_docs_slug: php
          template_file: ./README.template.md
          output_file: ./README.md

      - uses: google-github-actions/release-please-action@v3
        name: Release Please
        id: release
        with:
          token: ${{ secrets.MOMENTO_MACHINE_USER_GITHUB_TOKEN }}
          release-type: php
          package-name: momentohq/client-sdk-php
          extra-files: |
            src/Cache/Interceptors/AgentInterceptor.php
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'

      - name: Publish
        run: |
          echo "Published version: ${{ steps.release.outputs.tag_name }}"
        if: ${{ steps.release.outputs.release_created }}
