name: On push to main

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TEST_AUTH_TOKEN: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}
      TEST_CACHE_NAME: php-integration-test-cache

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.MOMENTO_MACHINE_USER_GITHUB_TOKEN }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: grpc, protobuf
          tools: composer

      - name: Install dependencies
        run: composer install

      - name: Run tests
        run: php vendor/phpunit/phpunit/phpunit --configuration phpunit.xml

      - name: Run examples
        env:
          MOMENTO_AUTH_TOKEN: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}
        working-directory: ./examples
        run: |
          composer install
          php ./example.php
          php ./dictionary-example.php
          php ./list-example.php
          php ./set-example.php

      - name: Generate README
        uses: momentohq/standards-and-practices/github-actions/generate-and-commit-oss-readme@gh-actions-v2
        with:
          project_status: official
          project_stability: stable
          project_type: sdk
          sdk_language: PHP
          dev_docs_slug: php
          template_file: ./README.template.md
          output_file: ./README.md
